"""
多领域预置术语库
覆盖 AI/计算机科学、医学/药学、金融/经济学、法律/法规、工程/制造 等领域
"""

AI_CS_GLOSSARY = {
    # ==================== 通用 AI 术语 ====================
    "通用 AI": [
        ("Artificial Intelligence", "人工智能", "AI"),
        ("Machine Learning", "机器学习", "ML"),
        ("Deep Learning", "深度学习", "DL"),
        ("Neural Network", "神经网络", "NN"),
        ("Artificial Neural Network", "人工神经网络", "ANN"),
        ("Convolutional Neural Network", "卷积神经网络", "CNN"),
        ("Recurrent Neural Network", "循环神经网络", "RNN"),
        ("Long Short-Term Memory", "长短期记忆网络", "LSTM"),
        ("Gated Recurrent Unit", "门控循环单元", "GRU"),
        ("Transformer", "Transformer", "Transformer"),
        ("Attention Mechanism", "注意力机制", "Attention"),
        ("Self-Attention", "自注意力", "Self-Attention"),
        ("Multi-Head Attention", "多头注意力", "MHA"),
        ("Large Language Model", "大语言模型", "LLM"),
        ("Generative AI", "生成式 AI", "GenAI"),
        ("Foundation Model", "基础模型", "Foundation Model"),
        ("Generative Pre-trained Transformer", "生成式预训练变换模型", "GPT"),
        ("Reinforcement Learning", "强化学习", "RL"),
        ("Supervised Learning", "监督学习", ""),
        ("Unsupervised Learning", "无监督学习", ""),
        ("Semi-Supervised Learning", "半监督学习", ""),
        ("Self-Supervised Learning", "自监督学习", ""),
        ("Transfer Learning", "迁移学习", ""),
        ("Few-Shot Learning", "少样本学习", ""),
        ("Zero-Shot Learning", "零样本学习", ""),
        ("Meta-Learning", "元学习", ""),
        ("Federated Learning", "联邦学习", ""),
        ("Active Learning", "主动学习", ""),
        ("Online Learning", "在线学习", ""),
        ("Ensemble Learning", "集成学习", ""),
    ],
    # ==================== NLP 术语 ====================
    "NLP": [
        ("Natural Language Processing", "自然语言处理", "NLP"),
        ("Natural Language Understanding", "自然语言理解", "NLU"),
        ("Natural Language Generation", "自然语言生成", "NLG"),
        ("Tokenization", "分词", ""),
        ("Word Embedding", "词嵌入", ""),
        ("Sentence Embedding", "句嵌入", ""),
        ("Positional Encoding", "位置编码", ""),
        ("Language Model", "语言模型", "LM"),
        ("Masked Language Model", "掩码语言模型", "MLM"),
        ("Next Token Prediction", "下一个 Token 预测", ""),
        ("Beam Search", "束搜索", ""),
        ("Text Classification", "文本分类", ""),
        ("Named Entity Recognition", "命名实体识别", "NER"),
        ("Part-of-Speech Tagging", "词性标注", "POS"),
        ("Dependency Parsing", "依存句法分析", ""),
        ("Sentiment Analysis", "情感分析", ""),
        ("Text Summarization", "文本摘要", ""),
        ("Machine Translation", "机器翻译", "MT"),
        ("Question Answering", "问答系统", "QA"),
        ("Information Retrieval", "信息检索", "IR"),
        ("Information Extraction", "信息抽取", "IE"),
        ("Text-to-Text Transfer Transformer", "文本到文本迁移变换器", "T5"),
        ("Bidirectional Encoder Representations", "双向编码器表示", "BERT"),
        ("Generative Pre-trained Transformer 2", "生成式预训练变换模型 2", "GPT-2"),
        ("Text-to-Text Transfer Transformer", "文本到文本迁移模型", "T5"),
        ("Cross-lingual Language Model", "跨语言语言模型", "XLM"),
        ("Sequence-to-Sequence", "序列到序列", "Seq2Seq"),
        ("Encoder-Decoder", "编码器-解码器", ""),
        ("Pointer-Generator Network", "指针生成网络", "PGN"),
        ("Retrieval-Augmented Generation", "检索增强生成", "RAG"),
        ("In-Context Learning", "上下文学习", "ICL"),
        ("Chain-of-Thought", "思维链", "CoT"),
        ("Prompt Engineering", "提示工程", ""),
        ("Prompt Tuning", "提示调优", ""),
        ("Instruction Tuning", "指令微调", ""),
    ],
    # ==================== 计算机视觉 ====================
    "计算机视觉": [
        ("Computer Vision", "计算机视觉", "CV"),
        ("Image Classification", "图像分类", ""),
        ("Object Detection", "目标检测", ""),
        ("Semantic Segmentation", "语义分割", ""),
        ("Instance Segmentation", "实例分割", ""),
        ("Panoptic Segmentation", "全景分割", ""),
        ("Object Tracking", "目标跟踪", ""),
        ("Image Generation", "图像生成", ""),
        ("Image-to-Image Translation", "图像到图像转换", ""),
        ("Image Super-Resolution", "图像超分辨率", ""),
        ("Image Denoising", "图像去噪", ""),
        ("Image Restoration", "图像复原", ""),
        ("Feature Extraction", "特征提取", ""),
        ("Feature Map", "特征图", ""),
        ("Feature Pyramid Network", "特征金字塔网络", "FPN"),
        ("Region-based CNN", "基于区域的卷积神经网络", "R-CNN"),
        ("You Only Look Once", "你只需看一次", "YOLO"),
        ("Single Shot MultiBox Detector", "单次多框检测器", "SSD"),
        ("Visual Transformer", "视觉变换器", "ViT"),
        ("Vision Transformer", "视觉变换器", "ViT"),
        ("Swin Transformer", "滑动窗口变换器", "Swin"),
        ("Diffusion Model", "扩散模型", ""),
        ("Denoising Diffusion Probabilistic Model", "去噪扩散概率模型", "DDPM"),
        ("Stable Diffusion", "稳定扩散", "Stable Diffusion"),
        ("Generative Adversarial Network", "生成对抗网络", "GAN"),
        ("Variational Autoencoder", "变分自编码器", "VAE"),
        ("Autoregressive Model", "自回归模型", ""),
        ("Optical Character Recognition", "光学字符识别", "OCR"),
        ("Facial Recognition", "人脸识别", ""),
        ("Pose Estimation", "姿态估计", ""),
        ("Depth Estimation", "深度估计", ""),
        ("Optical Flow", "光流", ""),
    ],
    # ==================== 大模型相关 ====================
    "大模型": [
        ("Parameter", "参数", ""),
        ("Hyperparameter", "超参数", ""),
        ("Fine-tuning", "微调", ""),
        ("Pre-training", "预训练", ""),
        ("Post-training", "后训练", ""),
        ("Full Fine-tuning", "全量微调", ""),
        ("Parameter-Efficient Fine-Tuning", "参数高效微调", "PEFT"),
        ("Low-Rank Adaptation", "低秩适应", "LoRA"),
        ("Quantization", "量化", ""),
        ("Knowledge Distillation", "知识蒸馏", ""),
        ("Model Compression", "模型压缩", ""),
        ("Pruning", "剪枝", ""),
        ("Mixed Precision Training", "混合精度训练", ""),
        ("Gradient Accumulation", "梯度累积", ""),
        ("Learning Rate", "学习率", "LR"),
        ("Batch Size", "批量大小", ""),
        ("Epoch", "训练轮次", ""),
        ("Loss Function", "损失函数", ""),
        ("Cross-Entropy Loss", "交叉熵损失", ""),
        ("Optimization", "优化", ""),
        ("Optimizer", "优化器", ""),
        ("Adam Optimizer", "Adam 优化器", "Adam"),
        ("Stochastic Gradient Descent", "随机梯度下降", "SGD"),
        ("Backpropagation", "反向传播", "BP"),
        ("Gradient Descent", "梯度下降", ""),
        ("Gradient Clipping", "梯度裁剪", ""),
        ("Weight Decay", "权重衰减", ""),
        ("Dropout", "随机失活", ""),
        ("Batch Normalization", "批归一化", "BN"),
        ("Layer Normalization", "层归一化", "LN"),
        ("Residual Connection", "残差连接", ""),
        ("Activation Function", "激活函数", ""),
        ("ReLU", "线性整流函数", "ReLU"),
        ("Sigmoid", "Sigmoid 函数", ""),
        ("Softmax", "Softmax 函数", ""),
        ("Context Window", "上下文窗口", ""),
        ("Token", "词元", ""),
        ("Vocabulary", "词表", ""),
        ("Embedding", "嵌入", ""),
        ("Latent Space", "潜在空间", ""),
        ("Inference", "推理", ""),
        ("Hallucination", "幻觉", ""),
        ("Alignment", "对齐", ""),
        ("RLHF", "基于人类反馈的强化学习", "RLHF"),
        ("Constitutional AI", "宪法 AI", "CAI"),
        ("Red Teaming", "红队测试", ""),
        ("Scaling Laws", "缩放定律", ""),
        ("Emergent Ability", "涌现能力", ""),
        ("In-Context Learning", "上下文学习", "ICL"),
        ("Tool Use", "工具使用", ""),
        ("Function Calling", "函数调用", ""),
        ("Agent", "智能体", ""),
        ("Multi-Agent", "多智能体", ""),
        ("Retrieval-Augmented Generation", "检索增强生成", "RAG"),
        ("Vector Database", "向量数据库", ""),
        ("Embedding Model", "嵌入模型", ""),
    ],
    # ==================== 数学与统计 ====================
    "数学与统计": [
        ("Linear Algebra", "线性代数", ""),
        ("Matrix Multiplication", "矩阵乘法", ""),
        ("Eigenvalue", "特征值", ""),
        ("Eigenvector", "特征向量", ""),
        ("Singular Value Decomposition", "奇异值分解", "SVD"),
        ("Principal Component Analysis", "主成分分析", "PCA"),
        ("Probability Distribution", "概率分布", ""),
        ("Bayesian", "贝叶斯", ""),
        ("Maximum Likelihood Estimation", "最大似然估计", "MLE"),
        ("Markov Chain", "马尔可夫链", ""),
        ("Monte Carlo", "蒙特卡洛", ""),
        ("Gaussian Distribution", "高斯分布", ""),
        ("Normal Distribution", "正态分布", ""),
        ("Gradient", "梯度", ""),
        ("Hessian Matrix", "海森矩阵", ""),
        ("Jacobian Matrix", "雅可比矩阵", ""),
        ("Chain Rule", "链式法则", ""),
        ("Partial Derivative", "偏导数", ""),
        ("Taylor Expansion", "泰勒展开", ""),
        ("Fourier Transform", "傅里叶变换", ""),
        ("Laplace Transform", "拉普拉斯变换", ""),
        ("Convex Optimization", "凸优化", ""),
        ("Lagrange Multiplier", "拉格朗日乘子", ""),
        ("KL Divergence", "KL 散度", ""),
        ("Cross-Entropy", "交叉熵", ""),
        ("Mutual Information", "互信息", ""),
        ("Entropy", "熵", ""),
        ("Information Gain", "信息增益", ""),
    ],
    # ==================== 软件工程 ====================
    "软件工程": [
        ("Application Programming Interface", "应用程序编程接口", "API"),
        ("Software Development Kit", "软件开发工具包", "SDK"),
        ("Integrated Development Environment", "集成开发环境", "IDE"),
        ("Version Control", "版本控制", ""),
        ("Continuous Integration", "持续集成", "CI"),
        ("Continuous Deployment", "持续部署", "CD"),
        ("Containerization", "容器化", ""),
        ("Microservices", "微服务", ""),
        ("Load Balancing", "负载均衡", ""),
        ("Cache", "缓存", ""),
        ("Database", "数据库", ""),
        ("Data Warehouse", "数据仓库", ""),
        ("Data Lake", "数据湖", ""),
        ("Extract Transform Load", "提取转换加载", "ETL"),
        ("Online Analytical Processing", "联机分析处理", "OLAP"),
        ("Online Transaction Processing", "联机事务处理", "OLTP"),
        ("Structured Query Language", "结构化查询语言", "SQL"),
        ("Not Only SQL", "非关系型数据库", "NoSQL"),
        ("Object-Relational Mapping", "对象关系映射", "ORM"),
        ("Representational State Transfer", "表述性状态转移", "REST"),
        ("Graph Query Language", "图查询语言", "GraphQL"),
        ("Remote Procedure Call", "远程过程调用", "RPC"),
        ("Message Queue", "消息队列", "MQ"),
        ("Publish-Subscribe", "发布-订阅", "Pub/Sub"),
        ("Event-Driven Architecture", "事件驱动架构", "EDA"),
        ("Domain-Driven Design", "领域驱动设计", "DDD"),
        ("Test-Driven Development", "测试驱动开发", "TDD"),
        ("Behavior-Driven Development", "行为驱动开发", "BDD"),
        ("DevOps", "开发运维一体化", ""),
        ("Infrastructure as Code", "基础设施即代码", "IaC"),
        ("Platform as a Service", "平台即服务", "PaaS"),
        ("Infrastructure as a Service", "基础设施即服务", "IaaS"),
        ("Software as a Service", "软件即服务", "SaaS"),
    ],
    # ==================== 数据科学 ====================
    "数据科学": [
        ("Data Mining", "数据挖掘", ""),
        ("Data Preprocessing", "数据预处理", ""),
        ("Data Augmentation", "数据增强", ""),
        ("Feature Engineering", "特征工程", ""),
        ("Feature Selection", "特征选择", ""),
        ("Dimensionality Reduction", "降维", ""),
        ("Overfitting", "过拟合", ""),
        ("Underfitting", "欠拟合", ""),
        ("Regularization", "正则化", ""),
        ("L1 Regularization", "L1 正则化", "Lasso"),
        ("L2 Regularization", "L2 正则化", "Ridge"),
        ("Early Stopping", "早停", ""),
        ("Cross-Validation", "交叉验证", ""),
        ("Holdout Validation", "留出验证", ""),
        ("K-Fold Cross Validation", "K 折交叉验证", ""),
        ("Confusion Matrix", "混淆矩阵", ""),
        ("Precision", "精确率", ""),
        ("Recall", "召回率", ""),
        ("F1 Score", "F1 分数", ""),
        ("Accuracy", "准确率", ""),
        ("ROC Curve", "ROC 曲线", ""),
        ("AUC", "曲线下面积", "AUC"),
        ("Mean Squared Error", "均方误差", "MSE"),
        ("Root Mean Squared Error", "均方根误差", "RMSE"),
        ("Mean Absolute Error", "平均绝对误差", "MAE"),
        ("R-squared", "决定系数", "R²"),
        ("Statistical Hypothesis Testing", "统计假设检验", ""),
        ("P-value", "P 值", ""),
        ("Confidence Interval", "置信区间", ""),
        ("Correlation Coefficient", "相关系数", ""),
        ("Standard Deviation", "标准差", ""),
        ("Variance", "方差", ""),
    ],
    # ==================== 云计算与分布式 ====================
    "云计算": [
        ("Cloud Computing", "云计算", ""),
        ("Edge Computing", "边缘计算", ""),
        ("Fog Computing", "雾计算", ""),
        ("Serverless Computing", "无服务器计算", ""),
        ("Function as a Service", "函数即服务", "FaaS"),
        ("Container Orchestration", "容器编排", ""),
        ("Kubernetes", "Kubernetes", "K8s"),
        ("Docker", "Docker", ""),
        ("Virtual Machine", "虚拟机", "VM"),
        ("Bare Metal Server", "裸金属服务器", ""),
        ("Elastic Scaling", "弹性伸缩", ""),
        ("Auto Scaling", "自动扩缩容", ""),
        ("Content Delivery Network", "内容分发网络", "CDN"),
        ("Distributed System", "分布式系统", ""),
        ("Distributed Computing", "分布式计算", ""),
        ("Parallel Computing", "并行计算", ""),
        ("High Performance Computing", "高性能计算", "HPC"),
        ("Graphics Processing Unit", "图形处理器", "GPU"),
        ("Tensor Processing Unit", "张量处理单元", "TPU"),
        ("Neural Processing Unit", "神经处理单元", "NPU"),
        ("Field Programmable Gate Array", "现场可编程门阵列", "FPGA"),
        ("Application-Specific Integrated Circuit", "专用集成电路", "ASIC"),
    ],
}

# ==================== 医学/药学 术语库 ====================
MEDICAL_GLOSSARY = {
    "医学通用": [
        ("Diagnosis", "诊断", ""),
        ("Treatment", "治疗", ""),
        ("Patient", "患者", ""),
        ("Clinical Trial", "临床试验", ""),
        ("Symptom", "症状", ""),
        ("Syndrome", "综合征", ""),
        ("Prognosis", "预后", ""),
        ("Remission", "缓解", ""),
        ("Relapse", "复发", ""),
        ("Mortality", "死亡率", ""),
        ("Morbidity", "发病率", ""),
        ("Etiology", "病因学", ""),
        ("Pathology", "病理学", ""),
        ("Pathophysiology", "病理生理学", ""),
        ("Epidemiology", "流行病学", ""),
        ("Systematic Review", "系统评价", ""),
        ("Meta-Analysis", "荟萃分析", ""),
        ("Contraindication", "禁忌症", ""),
        ("Indication", "适应症", ""),
        ("Adverse Event", "不良事件", ""),
        ("Side Effect", "副作用", ""),
        ("Complication", "并发症", ""),
        ("Comorbidity", "合并症", ""),
        ("First-Line Treatment", "一线治疗", ""),
        ("Standard of Care", "标准治疗方案", ""),
        ("Evidence-Based Medicine", "循证医学", ""),
        ("Precision Medicine", "精准医疗", ""),
        ("Personalized Medicine", "个体化医疗", ""),
        ("Regenerative Medicine", "再生医学", ""),
        ("Translational Medicine", "转化医学", ""),
    ],
    "肿瘤学": [
        ("Tumor", "肿瘤", ""),
        ("Malignant", "恶性", ""),
        ("Benign", "良性", ""),
        ("Carcinoma", "癌", ""),
        ("Sarcoma", "肉瘤", ""),
        ("Lymphoma", "淋巴瘤", ""),
        ("Leukemia", "白血病", ""),
        ("Metastasis", "转移", ""),
        ("Biopsy", "活检", ""),
        ("Chemotherapy", "化疗", ""),
        ("Radiotherapy", "放疗", ""),
        ("Immunotherapy", "免疫治疗", ""),
        ("Targeted Therapy", "靶向治疗", ""),
        ("Hormone Therapy", "激素治疗", ""),
        ("Oncogene", "癌基因", ""),
        ("Tumor Suppressor Gene", "抑癌基因", ""),
        ("Programmed Cell Death", "程序性细胞死亡", ""),
        ("Apoptosis", "凋亡", ""),
        ("Necrosis", "坏死", ""),
        ("Angiogenesis", "血管生成", ""),
        ("Carcinogenesis", "癌变", ""),
        ("Cancer Staging", "癌症分期", ""),
        ("TNM Classification", "TNM分期", ""),
        ("Overall Survival", "总生存期", ""),
        ("Progression-Free Survival", "无进展生存期", ""),
    ],
    "药学": [
        ("Pharmacology", "药理学", ""),
        ("Pharmacokinetics", "药代动力学", ""),
        ("Pharmacodynamics", "药效动力学", ""),
        ("Bioavailability", "生物利用度", ""),
        ("Half-Life", "半衰期", ""),
        ("Clearance", "清除率", ""),
        ("Metabolism", "代谢", ""),
        ("Excretion", "排泄", ""),
        ("Absorption", "吸收", ""),
        ("Distribution", "分布", ""),
        ("Dose", "剂量", ""),
        ("Dosage", "给药方案", ""),
        ("Placebo", "安慰剂", ""),
        ("Double-Blind", "双盲", ""),
        ("Randomized Controlled Trial", "随机对照试验", ""),
        ("Active Ingredient", "活性成分", ""),
        ("Formulation", "制剂", ""),
        ("Generic Drug", "仿制药", ""),
        ("Biologic", "生物制剂", ""),
        ("Biosimilar", "生物类似药", ""),
        ("Receptor", "受体", ""),
        ("Agonist", "激动剂", ""),
        ("Antagonist", "拮抗剂", ""),
        ("Inhibitor", "抑制剂", ""),
        ("Antibody", "抗体", ""),
        ("Monoclonal Antibody", "单克隆抗体", ""),
        ("Enzyme", "酶", ""),
        ("Small Molecule", "小分子", ""),
        ("Peptide", "肽", ""),
        ("Vaccine", "疫苗", ""),
    ],
}


# ==================== 金融/经济学 术语库 ====================
FINANCE_GLOSSARY = {
    "金融基础": [
        ("Asset", "资产", ""),
        ("Liability", "负债", ""),
        ("Equity", "权益", ""),
        ("Revenue", "收入", ""),
        ("Expense", "费用", ""),
        ("Profit", "利润", ""),
        ("Loss", "亏损", ""),
        ("Margin", "利润率", ""),
        ("Dividend", "股息", ""),
        ("Yield", "收益率", ""),
        ("Return on Investment", "投资回报率", "ROI"),
        ("Net Present Value", "净现值", "NPV"),
        ("Internal Rate of Return", "内部收益率", "IRR"),
        ("Earnings Per Share", "每股收益", "EPS"),
        ("Price-Earnings Ratio", "市盈率", "P/E"),
        ("Book Value", "账面价值", ""),
        ("Market Capitalization", "市值", ""),
        ("Enterprise Value", "企业价值", "EV"),
        ("EBITDA", "息税折旧摊销前利润", "EBITDA"),
        ("Free Cash Flow", "自由现金流", "FCF"),
        ("Working Capital", "营运资本", ""),
        ("Debt-to-Equity Ratio", "负债权益比", "D/E"),
        ("Current Ratio", "流动比率", ""),
        ("Quick Ratio", "速动比率", ""),
    ],
    "投资与市场": [
        ("Stock", "股票", ""),
        ("Bond", "债券", ""),
        ("Security", "证券", ""),
        ("Derivative", "衍生品", ""),
        ("Option", "期权", ""),
        ("Futures", "期货", ""),
        ("Swap", "互换", ""),
        ("Forward Contract", "远期合约", ""),
        ("Initial Public Offering", "首次公开发行", "IPO"),
        ("Secondary Offering", "增发", ""),
        ("Diversification", "分散投资", ""),
        ("Hedge", "对冲", ""),
        ("Arbitrage", "套利", ""),
        ("Bull Market", "牛市", ""),
        ("Bear Market", "熊市", ""),
        ("Volatility", "波动率", ""),
        ("Liquidity", "流动性", ""),
        ("Benchmark", "基准", ""),
        ("Index Fund", "指数基金", ""),
        ("Exchange-Traded Fund", "交易所交易基金", "ETF"),
        ("Mutual Fund", "共同基金", ""),
        ("Hedge Fund", "对冲基金", ""),
        ("Private Equity", "私募股权", ""),
        ("Venture Capital", "风险投资", ""),
        ("Angel Investor", "天使投资人", ""),
    ],
    "经济与政策": [
        ("Gross Domestic Product", "国内生产总值", "GDP"),
        ("Consumer Price Index", "消费者价格指数", "CPI"),
        ("Purchasing Power Parity", "购买力平价", "PPP"),
        ("Inflation", "通货膨胀", ""),
        ("Deflation", "通货紧缩", ""),
        ("Stagflation", "滞胀", ""),
        ("Recession", "衰退", ""),
        ("Fiscal Policy", "财政政策", ""),
        ("Monetary Policy", "货币政策", ""),
        ("Interest Rate", "利率", ""),
        ("Exchange Rate", "汇率", ""),
        ("Balance of Trade", "贸易差额", ""),
        ("Current Account", "经常账户", ""),
        ("Sovereign Debt", "主权债务", ""),
        ("Quantitative Easing", "量化宽松", ""),
        ("Supply and Demand", "供给与需求", ""),
        ("Elasticity", "弹性", ""),
        ("Opportunity Cost", "机会成本", ""),
        ("Marginal Utility", "边际效用", ""),
        ("Comparative Advantage", "比较优势", ""),
        ("Free Trade", "自由贸易", ""),
        ("Tariff", "关税", ""),
        ("Subsidy", "补贴", ""),
        ("Market Failure", "市场失灵", ""),
        ("Externalities", "外部性", ""),
    ],
}


# ==================== 法律/法规 术语库 ====================
LEGAL_GLOSSARY = {
    "法律通用": [
        ("Statute", "法规", ""),
        ("Regulation", "条例", ""),
        ("Legislation", "立法", ""),
        ("Jurisdiction", "管辖权", ""),
        ("Plaintiff", "原告", ""),
        ("Defendant", "被告", ""),
        ("Litigation", "诉讼", ""),
        ("Arbitration", "仲裁", ""),
        ("Mediation", "调解", ""),
        ("Contract", "合同", ""),
        ("Agreement", "协议", ""),
        ("Breach of Contract", "违约", ""),
        ("Damages", "损害赔偿", ""),
        ("Indemnity", "赔偿", ""),
        ("Liability", "责任", ""),
        ("Negligence", "过失", ""),
        ("Tort", "侵权", ""),
        ("Remedy", "救济", ""),
        ("Intellectual Property", "知识产权", ""),
        ("Patent", "专利", ""),
        ("Copyright", "版权", ""),
        ("Trademark", "商标", ""),
        ("Trade Secret", "商业秘密", ""),
        ("Compliance", "合规", ""),
        ("Due Diligence", "尽职调查", ""),
        ("Force Majeure", "不可抗力", ""),
        ("Confidentiality", "保密", ""),
        ("Non-Disclosure Agreement", "保密协议", "NDA"),
        ("Memorandum of Understanding", "谅解备忘录", "MOU"),
        ("Terms and Conditions", "条款与条件", ""),
    ],
}


# ==================== 工程/制造 术语库 ====================
ENGINEERING_GLOSSARY = {
    "工程通用": [
        ("Mechanism", "机构", ""),
        ("Component", "组件", ""),
        ("Assembly", "装配", ""),
        ("Fabrication", "制造", ""),
        ("Tolerance", "公差", ""),
        ("Specification", "规格", ""),
        ("Prototype", "原型", ""),
        ("Simulation", "仿真", ""),
        ("Finite Element Analysis", "有限元分析", "FEA"),
        ("Computational Fluid Dynamics", "计算流体力学", "CFD"),
        ("Thermodynamics", "热力学", ""),
        ("Fluid Dynamics", "流体动力学", ""),
        ("Stress Analysis", "应力分析", ""),
        ("Fatigue", "疲劳", ""),
        ("Corrosion", "腐蚀", ""),
        ("Actuator", "执行器", ""),
        ("Sensor", "传感器", ""),
        ("Controller", "控制器", ""),
        ("Automation", "自动化", ""),
        ("Robotics", "机器人", ""),
        ("Quality Control", "质量控制", "QC"),
        ("Six Sigma", "六西格玛", ""),
        ("Lean Manufacturing", "精益制造", ""),
        ("Supply Chain", "供应链", ""),
        ("Logistics", "物流", ""),
        ("Reliability", "可靠性", ""),
        ("Maintenance", "维护", ""),
        ("Mean Time Between Failures", "平均故障间隔时间", "MTBF"),
        ("Mean Time To Repair", "平均修复时间", "MTTR"),
    ],
}


ALL_PRESET_GLOSSARIES = {
    **{f"AI/{k}": v for k, v in AI_CS_GLOSSARY.items()},
    **{f"医学/{k}": v for k, v in MEDICAL_GLOSSARY.items()},
    **{f"金融/{k}": v for k, v in FINANCE_GLOSSARY.items()},
    **{f"法律/{k}": v for k, v in LEGAL_GLOSSARY.items()},
    **{f"工程/{k}": v for k, v in ENGINEERING_GLOSSARY.items()},
}


def get_all_terms(domain: str = None) -> list:
    """获取所有术语列表
    
    Args:
        domain: 可选，仅获取指定领域的术语（如 "AI/通用 AI", "医学/肿瘤学"）
    """
    terms = []
    source = ALL_PRESET_GLOSSARIES
    if domain:
        source = {domain: ALL_PRESET_GLOSSARIES.get(domain, [])}
    for domain_name, term_list in source.items():
        for term, translation, abbreviation in term_list:
            terms.append({
                "term": term,
                "translation": translation,
                "lang_in": "en",
                "lang_out": "zh",
                "domain": domain_name,
                "description": abbreviation,
            })
    return terms


def get_terms_by_domain(domain: str) -> list:
    """获取指定领域的术语"""
    return get_all_terms(domain=domain)


def get_domains() -> list:
    """获取所有顶级领域列表"""
    top_domains = set()
    for key in ALL_PRESET_GLOSSARIES:
        top = key.split("/")[0]
        top_domains.add(top)
    return sorted(top_domains)


def get_sub_domains(top_domain: str = None) -> list:
    """获取所有子领域列表
    
    Args:
        top_domain: 顶级领域名（如 "AI"），为 None 返回全部
    """
    if top_domain:
        return [k for k in ALL_PRESET_GLOSSARIES if k.startswith(top_domain + "/")]
    return list(ALL_PRESET_GLOSSARIES.keys())


if __name__ == "__main__":
    total = sum(len(v) for v in ALL_PRESET_GLOSSARIES.values())
    print(f"多领域术语库统计:")
    print(f"  总术语数: {total}")
    print(f"  子领域数: {len(ALL_PRESET_GLOSSARIES)}")
    top = {}
    for domain_name, terms in ALL_PRESET_GLOSSARIES.items():
        top_key = domain_name.split("/")[0]
        top[top_key] = top.get(top_key, 0) + len(terms)
    for k, v in sorted(top.items()):
        print(f"  {k}: {v} 条")