"""
多领域预置术语库
覆盖 AI/计算机科学、医学/药学、金融/经济学、法律/法规、工程/制造 等领域
"""

AI_CS_GLOSSARY = {
    # ==================== 通用 AI 术语 ====================
    "通用 AI": [
        ("Artificial Intelligence", "人工智能", "AI"),
        ("Machine Learning", "机器学习", "ML"),
        ("Deep Learning", "深度学习", "DL"),
        ("Neural Network", "神经网络", "NN"),
        ("Artificial Neural Network", "人工神经网络", "ANN"),
        ("Convolutional Neural Network", "卷积神经网络", "CNN"),
        ("Recurrent Neural Network", "循环神经网络", "RNN"),
        ("Long Short-Term Memory", "长短期记忆网络", "LSTM"),
        ("Gated Recurrent Unit", "门控循环单元", "GRU"),
        ("Transformer", "Transformer", "Transformer"),
        ("Attention Mechanism", "注意力机制", "Attention"),
        ("Self-Attention", "自注意力", "Self-Attention"),
        ("Multi-Head Attention", "多头注意力", "MHA"),
        ("Large Language Model", "大语言模型", "LLM"),
        ("Generative AI", "生成式 AI", "GenAI"),
        ("Foundation Model", "基础模型", "Foundation Model"),
        ("Generative Pre-trained Transformer", "生成式预训练变换模型", "GPT"),
        ("Reinforcement Learning", "强化学习", "RL"),
        ("Supervised Learning", "监督学习", ""),
        ("Unsupervised Learning", "无监督学习", ""),
        ("Semi-Supervised Learning", "半监督学习", ""),
        ("Self-Supervised Learning", "自监督学习", ""),
        ("Transfer Learning", "迁移学习", ""),
        ("Few-Shot Learning", "少样本学习", ""),
        ("Zero-Shot Learning", "零样本学习", ""),
        ("Meta-Learning", "元学习", ""),
        ("Federated Learning", "联邦学习", ""),
        ("Active Learning", "主动学习", ""),
        ("Online Learning", "在线学习", ""),
        ("Ensemble Learning", "集成学习", ""),
    ],
    # ==================== NLP 术语 ====================
    "NLP": [
        ("Natural Language Processing", "自然语言处理", "NLP"),
        ("Natural Language Understanding", "自然语言理解", "NLU"),
        ("Natural Language Generation", "自然语言生成", "NLG"),
        ("Tokenization", "分词", ""),
        ("Word Embedding", "词嵌入", ""),
        ("Sentence Embedding", "句嵌入", ""),
        ("Positional Encoding", "位置编码", ""),
        ("Language Model", "语言模型", "LM"),
        ("Masked Language Model", "掩码语言模型", "MLM"),
        ("Next Token Prediction", "下一个 Token 预测", ""),
        ("Beam Search", "束搜索", ""),
        ("Text Classification", "文本分类", ""),
        ("Named Entity Recognition", "命名实体识别", "NER"),
        ("Part-of-Speech Tagging", "词性标注", "POS"),
        ("Dependency Parsing", "依存句法分析", ""),
        ("Sentiment Analysis", "情感分析", ""),
        ("Text Summarization", "文本摘要", ""),
        ("Machine Translation", "机器翻译", "MT"),
        ("Question Answering", "问答系统", "QA"),
        ("Information Retrieval", "信息检索", "IR"),
        ("Information Extraction", "信息抽取", "IE"),
        ("Text-to-Text Transfer Transformer", "文本到文本迁移变换器", "T5"),
        ("Bidirectional Encoder Representations", "双向编码器表示", "BERT"),
        ("Generative Pre-trained Transformer 2", "生成式预训练变换模型 2", "GPT-2"),
        ("Text-to-Text Transfer Transformer", "文本到文本迁移模型", "T5"),
        ("Cross-lingual Language Model", "跨语言语言模型", "XLM"),
        ("Sequence-to-Sequence", "序列到序列", "Seq2Seq"),
        ("Encoder-Decoder", "编码器-解码器", ""),
        ("Pointer-Generator Network", "指针生成网络", "PGN"),
        ("Retrieval-Augmented Generation", "检索增强生成", "RAG"),
        ("In-Context Learning", "上下文学习", "ICL"),
        ("Chain-of-Thought", "思维链", "CoT"),
        ("Prompt Engineering", "提示工程", ""),
        ("Prompt Tuning", "提示调优", ""),
        ("Instruction Tuning", "指令微调", ""),
    ],
    # ==================== 计算机视觉 ====================
    "计算机视觉": [
        ("Computer Vision", "计算机视觉", "CV"),
        ("Image Classification", "图像分类", ""),
        ("Object Detection", "目标检测", ""),
        ("Semantic Segmentation", "语义分割", ""),
        ("Instance Segmentation", "实例分割", ""),
        ("Panoptic Segmentation", "全景分割", ""),
        ("Object Tracking", "目标跟踪", ""),
        ("Image Generation", "图像生成", ""),
        ("Image-to-Image Translation", "图像到图像转换", ""),
        ("Image Super-Resolution", "图像超分辨率", ""),
        ("Image Denoising", "图像去噪", ""),
        ("Image Restoration", "图像复原", ""),
        ("Feature Extraction", "特征提取", ""),
        ("Feature Map", "特征图", ""),
        ("Feature Pyramid Network", "特征金字塔网络", "FPN"),
        ("Region-based CNN", "基于区域的卷积神经网络", "R-CNN"),
        ("You Only Look Once", "你只需看一次", "YOLO"),
        ("Single Shot MultiBox Detector", "单次多框检测器", "SSD"),
        ("Visual Transformer", "视觉变换器", "ViT"),
        ("Vision Transformer", "视觉变换器", "ViT"),
        ("Swin Transformer", "滑动窗口变换器", "Swin"),
        ("Diffusion Model", "扩散模型", ""),
        ("Denoising Diffusion Probabilistic Model", "去噪扩散概率模型", "DDPM"),
        ("Stable Diffusion", "稳定扩散", "Stable Diffusion"),
        ("Generative Adversarial Network", "生成对抗网络", "GAN"),
        ("Variational Autoencoder", "变分自编码器", "VAE"),
        ("Autoregressive Model", "自回归模型", ""),
        ("Optical Character Recognition", "光学字符识别", "OCR"),
        ("Facial Recognition", "人脸识别", ""),
        ("Pose Estimation", "姿态估计", ""),
        ("Depth Estimation", "深度估计", ""),
        ("Optical Flow", "光流", ""),
    ],
    # ==================== 大模型相关 ====================
    "大模型": [
        ("Parameter", "参数", ""),
        ("Hyperparameter", "超参数", ""),
        ("Fine-tuning", "微调", ""),
        ("Pre-training", "预训练", ""),
        ("Post-training", "后训练", ""),
        ("Full Fine-tuning", "全量微调", ""),
        ("Parameter-Efficient Fine-Tuning", "参数高效微调", "PEFT"),
        ("Low-Rank Adaptation", "低秩适应", "LoRA"),
        ("Quantization", "量化", ""),
        ("Knowledge Distillation", "知识蒸馏", ""),
        ("Model Compression", "模型压缩", ""),
        ("Pruning", "剪枝", ""),
        ("Mixed Precision Training", "混合精度训练", ""),
        ("Gradient Accumulation", "梯度累积", ""),
        ("Learning Rate", "学习率", "LR"),
        ("Batch Size", "批量大小", ""),
        ("Epoch", "训练轮次", ""),
        ("Loss Function", "损失函数", ""),
        ("Cross-Entropy Loss", "交叉熵损失", ""),
        ("Optimization", "优化", ""),
        ("Optimizer", "优化器", ""),
        ("Adam Optimizer", "Adam 优化器", "Adam"),
        ("Stochastic Gradient Descent", "随机梯度下降", "SGD"),
        ("Backpropagation", "反向传播", "BP"),
        ("Gradient Descent", "梯度下降", ""),
        ("Gradient Clipping", "梯度裁剪", ""),
        ("Weight Decay", "权重衰减", ""),
        ("Dropout", "随机失活", ""),
        ("Batch Normalization", "批归一化", "BN"),
        ("Layer Normalization", "层归一化", "LN"),
        ("Residual Connection", "残差连接", ""),
        ("Activation Function", "激活函数", ""),
        ("ReLU", "线性整流函数", "ReLU"),
        ("Sigmoid", "Sigmoid 函数", ""),
        ("Softmax", "Softmax 函数", ""),
        ("Context Window", "上下文窗口", ""),
        ("Token", "词元", ""),
        ("Vocabulary", "词表", ""),
        ("Embedding", "嵌入", ""),
        ("Latent Space", "潜在空间", ""),
        ("Inference", "推理", ""),
        ("Hallucination", "幻觉", ""),
        ("Alignment", "对齐", ""),
        ("RLHF", "基于人类反馈的强化学习", "RLHF"),
        ("Constitutional AI", "宪法 AI", "CAI"),
        ("Red Teaming", "红队测试", ""),
        ("Scaling Laws", "缩放定律", ""),
        ("Emergent Ability", "涌现能力", ""),
        ("In-Context Learning", "上下文学习", "ICL"),
        ("Tool Use", "工具使用", ""),
        ("Function Calling", "函数调用", ""),
        ("Agent", "智能体", ""),
        ("Multi-Agent", "多智能体", ""),
        ("Retrieval-Augmented Generation", "检索增强生成", "RAG"),
        ("Vector Database", "向量数据库", ""),
        ("Embedding Model", "嵌入模型", ""),
    ],
    # ==================== 数学与统计 ====================
    "数学与统计": [
        ("Linear Algebra", "线性代数", ""),
        ("Matrix Multiplication", "矩阵乘法", ""),
        ("Eigenvalue", "特征值", ""),
        ("Eigenvector", "特征向量", ""),
        ("Singular Value Decomposition", "奇异值分解", "SVD"),
        ("Principal Component Analysis", "主成分分析", "PCA"),
        ("Probability Distribution", "概率分布", ""),
        ("Bayesian", "贝叶斯", ""),
        ("Maximum Likelihood Estimation", "最大似然估计", "MLE"),
        ("Markov Chain", "马尔可夫链", ""),
        ("Monte Carlo", "蒙特卡洛", ""),
        ("Gaussian Distribution", "高斯分布", ""),
        ("Normal Distribution", "正态分布", ""),
        ("Gradient", "梯度", ""),
        ("Hessian Matrix", "海森矩阵", ""),
        ("Jacobian Matrix", "雅可比矩阵", ""),
        ("Chain Rule", "链式法则", ""),
        ("Partial Derivative", "偏导数", ""),
        ("Taylor Expansion", "泰勒展开", ""),
        ("Fourier Transform", "傅里叶变换", ""),
        ("Laplace Transform", "拉普拉斯变换", ""),
        ("Convex Optimization", "凸优化", ""),
        ("Lagrange Multiplier", "拉格朗日乘子", ""),
        ("KL Divergence", "KL 散度", ""),
        ("Cross-Entropy", "交叉熵", ""),
        ("Mutual Information", "互信息", ""),
        ("Entropy", "熵", ""),
        ("Information Gain", "信息增益", ""),
    ],
    # ==================== 软件工程 ====================
    "软件工程": [
        ("Application Programming Interface", "应用程序编程接口", "API"),
        ("Software Development Kit", "软件开发工具包", "SDK"),
        ("Integrated Development Environment", "集成开发环境", "IDE"),
        ("Version Control", "版本控制", ""),
        ("Continuous Integration", "持续集成", "CI"),
        ("Continuous Deployment", "持续部署", "CD"),
        ("Containerization", "容器化", ""),
        ("Microservices", "微服务", ""),
        ("Load Balancing", "负载均衡", ""),
        ("Cache", "缓存", ""),
        ("Database", "数据库", ""),
        ("Data Warehouse", "数据仓库", ""),
        ("Data Lake", "数据湖", ""),
        ("Extract Transform Load", "提取转换加载", "ETL"),
        ("Online Analytical Processing", "联机分析处理", "OLAP"),
        ("Online Transaction Processing", "联机事务处理", "OLTP"),
        ("Structured Query Language", "结构化查询语言", "SQL"),
        ("Not Only SQL", "非关系型数据库", "NoSQL"),
        ("Object-Relational Mapping", "对象关系映射", "ORM"),
        ("Representational State Transfer", "表述性状态转移", "REST"),
        ("Graph Query Language", "图查询语言", "GraphQL"),
        ("Remote Procedure Call", "远程过程调用", "RPC"),
        ("Message Queue", "消息队列", "MQ"),
        ("Publish-Subscribe", "发布-订阅", "Pub/Sub"),
        ("Event-Driven Architecture", "事件驱动架构", "EDA"),
        ("Domain-Driven Design", "领域驱动设计", "DDD"),
        ("Test-Driven Development", "测试驱动开发", "TDD"),
        ("Behavior-Driven Development", "行为驱动开发", "BDD"),
        ("DevOps", "开发运维一体化", ""),
        ("Infrastructure as Code", "基础设施即代码", "IaC"),
        ("Platform as a Service", "平台即服务", "PaaS"),
        ("Infrastructure as a Service", "基础设施即服务", "IaaS"),
        ("Software as a Service", "软件即服务", "SaaS"),
    ],
    # ==================== 数据科学 ====================
    "数据科学": [
        ("Data Mining", "数据挖掘", ""),
        ("Data Preprocessing", "数据预处理", ""),
        ("Data Augmentation", "数据增强", ""),
        ("Feature Engineering", "特征工程", ""),
        ("Feature Selection", "特征选择", ""),
        ("Dimensionality Reduction", "降维", ""),
        ("Overfitting", "过拟合", ""),
        ("Underfitting", "欠拟合", ""),
        ("Regularization", "正则化", ""),
        ("L1 Regularization", "L1 正则化", "Lasso"),
        ("L2 Regularization", "L2 正则化", "Ridge"),
        ("Early Stopping", "早停", ""),
        ("Cross-Validation", "交叉验证", ""),
        ("Holdout Validation", "留出验证", ""),
        ("K-Fold Cross Validation", "K 折交叉验证", ""),
        ("Confusion Matrix", "混淆矩阵", ""),
        ("Precision", "精确率", ""),
        ("Recall", "召回率", ""),
        ("F1 Score", "F1 分数", ""),
        ("Accuracy", "准确率", ""),
        ("ROC Curve", "ROC 曲线", ""),
        ("AUC", "曲线下面积", "AUC"),
        ("Mean Squared Error", "均方误差", "MSE"),
        ("Root Mean Squared Error", "均方根误差", "RMSE"),
        ("Mean Absolute Error", "平均绝对误差", "MAE"),
        ("R-squared", "决定系数", "R²"),
        ("Statistical Hypothesis Testing", "统计假设检验", ""),
        ("P-value", "P 值", ""),
        ("Confidence Interval", "置信区间", ""),
        ("Correlation Coefficient", "相关系数", ""),
        ("Standard Deviation", "标准差", ""),
        ("Variance", "方差", ""),
    ],
    # ==================== 云计算与分布式 ====================
    "云计算": [
        ("Cloud Computing", "云计算", ""),
        ("Edge Computing", "边缘计算", ""),
        ("Fog Computing", "雾计算", ""),
        ("Serverless Computing", "无服务器计算", ""),
        ("Function as a Service", "函数即服务", "FaaS"),
        ("Container Orchestration", "容器编排", ""),
        ("Kubernetes", "Kubernetes", "K8s"),
        ("Docker", "Docker", ""),
        ("Virtual Machine", "虚拟机", "VM"),
        ("Bare Metal Server", "裸金属服务器", ""),
        ("Elastic Scaling", "弹性伸缩", ""),
        ("Auto Scaling", "自动扩缩容", ""),
        ("Content Delivery Network", "内容分发网络", "CDN"),
        ("Distributed System", "分布式系统", ""),
        ("Distributed Computing", "分布式计算", ""),
        ("Parallel Computing", "并行计算", ""),
        ("High Performance Computing", "高性能计算", "HPC"),
        ("Graphics Processing Unit", "图形处理器", "GPU"),
        ("Tensor Processing Unit", "张量处理单元", "TPU"),
        ("Neural Processing Unit", "神经处理单元", "NPU"),
        ("Field Programmable Gate Array", "现场可编程门阵列", "FPGA"),
        ("Application-Specific Integrated Circuit", "专用集成电路", "ASIC"),
    ],
}

# ==================== 医学/药学 术语库 ====================
MEDICAL_GLOSSARY = {
    "医学通用": [
        ("Diagnosis", "诊断", ""),
        ("Treatment", "治疗", ""),
        ("Patient", "患者", ""),
        ("Clinical Trial", "临床试验", ""),
        ("Symptom", "症状", ""),
        ("Syndrome", "综合征", ""),
        ("Prognosis", "预后", ""),
        ("Remission", "缓解", ""),
        ("Relapse", "复发", ""),
        ("Mortality", "死亡率", ""),
        ("Morbidity", "发病率", ""),
        ("Etiology", "病因学", ""),
        ("Pathology", "病理学", ""),
        ("Pathophysiology", "病理生理学", ""),
        ("Epidemiology", "流行病学", ""),
        ("Systematic Review", "系统评价", ""),
        ("Meta-Analysis", "荟萃分析", ""),
        ("Contraindication", "禁忌症", ""),
        ("Indication", "适应症", ""),
        ("Adverse Event", "不良事件", ""),
        ("Side Effect", "副作用", ""),
        ("Complication", "并发症", ""),
        ("Comorbidity", "合并症", ""),
        ("First-Line Treatment", "一线治疗", ""),
        ("Standard of Care", "标准治疗方案", ""),
        ("Evidence-Based Medicine", "循证医学", ""),
        ("Precision Medicine", "精准医疗", ""),
        ("Personalized Medicine", "个体化医疗", ""),
        ("Regenerative Medicine", "再生医学", ""),
        ("Translational Medicine", "转化医学", ""),
    ],
    "肿瘤学": [
        ("Tumor", "肿瘤", ""),
        ("Malignant", "恶性", ""),
        ("Benign", "良性", ""),
        ("Carcinoma", "癌", ""),
        ("Sarcoma", "肉瘤", ""),
        ("Lymphoma", "淋巴瘤", ""),
        ("Leukemia", "白血病", ""),
        ("Metastasis", "转移", ""),
        ("Biopsy", "活检", ""),
        ("Chemotherapy", "化疗", ""),
        ("Radiotherapy", "放疗", ""),
        ("Immunotherapy", "免疫治疗", ""),
        ("Targeted Therapy", "靶向治疗", ""),
        ("Hormone Therapy", "激素治疗", ""),
        ("Oncogene", "癌基因", ""),
        ("Tumor Suppressor Gene", "抑癌基因", ""),
        ("Programmed Cell Death", "程序性细胞死亡", ""),
        ("Apoptosis", "凋亡", ""),
        ("Necrosis", "坏死", ""),
        ("Angiogenesis", "血管生成", ""),
        ("Carcinogenesis", "癌变", ""),
        ("Cancer Staging", "癌症分期", ""),
        ("TNM Classification", "TNM分期", ""),
        ("Overall Survival", "总生存期", ""),
        ("Progression-Free Survival", "无进展生存期", ""),
    ],
    "药学": [
        ("Pharmacology", "药理学", ""),
        ("Pharmacokinetics", "药代动力学", ""),
        ("Pharmacodynamics", "药效动力学", ""),
        ("Bioavailability", "生物利用度", ""),
        ("Half-Life", "半衰期", ""),
        ("Clearance", "清除率", ""),
        ("Metabolism", "代谢", ""),
        ("Excretion", "排泄", ""),
        ("Absorption", "吸收", ""),
        ("Distribution", "分布", ""),
        ("Dose", "剂量", ""),
        ("Dosage", "给药方案", ""),
        ("Placebo", "安慰剂", ""),
        ("Double-Blind", "双盲", ""),
        ("Randomized Controlled Trial", "随机对照试验", ""),
        ("Active Ingredient", "活性成分", ""),
        ("Formulation", "制剂", ""),
        ("Generic Drug", "仿制药", ""),
        ("Biologic", "生物制剂", ""),
        ("Biosimilar", "生物类似药", ""),
        ("Receptor", "受体", ""),
        ("Agonist", "激动剂", ""),
        ("Antagonist", "拮抗剂", ""),
        ("Inhibitor", "抑制剂", ""),
        ("Antibody", "抗体", ""),
        ("Monoclonal Antibody", "单克隆抗体", ""),
        ("Enzyme", "酶", ""),
        ("Small Molecule", "小分子", ""),
        ("Peptide", "肽", ""),
        ("Vaccine", "疫苗", ""),
    ],
    "心血管": [
        ("Cardiology", "心脏病学", ""),
        ("Coronary Artery Disease", "冠状动脉疾病", "CAD"),
        ("Myocardial Infarction", "心肌梗死", "MI"),
        ("Angina Pectoris", "心绞痛", ""),
        ("Heart Failure", "心力衰竭", ""),
        ("Arrhythmia", "心律失常", ""),
        ("Atrial Fibrillation", "心房颤动", "AF"),
        ("Ventricular Tachycardia", "室性心动过速", "VT"),
        ("Hypertension", "高血压", ""),
        ("Hypotension", "低血压", ""),
        ("Atherosclerosis", "动脉粥样硬化", ""),
        ("Ischemia", "缺血", ""),
        ("Ischemic Heart Disease", "缺血性心脏病", ""),
        ("Cardiac Arrest", "心脏骤停", ""),
        ("Cardiopulmonary Resuscitation", "心肺复苏", "CPR"),
        ("Echocardiography", "超声心动图", ""),
        ("Electrocardiogram", "心电图", "ECG"),
        ("Cardiac Catheterization", "心导管检查", ""),
        ("Angioplasty", "血管成形术", ""),
        ("Stent", "支架", ""),
        ("Coronary Bypass Surgery", "冠状动脉搭桥术", "CABG"),
        ("Valvular Heart Disease", "心脏瓣膜病", ""),
        ("Aortic Stenosis", "主动脉瓣狭窄", ""),
        ("Mitral Regurgitation", "二尖瓣反流", ""),
        ("Congenital Heart Disease", "先天性心脏病", ""),
        ("Cardiomyopathy", "心肌病", ""),
        ("Endocarditis", "心内膜炎", ""),
        ("Pericarditis", "心包炎", ""),
        ("Pulmonary Embolism", "肺栓塞", "PE"),
        ("Deep Vein Thrombosis", "深静脉血栓", "DVT"),
        ("Blood Pressure", "血压", "BP"),
    ],
    "神经系统": [
        ("Neurology", "神经病学", ""),
        ("Stroke", "卒中", ""),
        ("Ischemic Stroke", "缺血性脑卒中", ""),
        ("Hemorrhagic Stroke", "出血性脑卒中", ""),
        ("Transient Ischemic Attack", "短暂性脑缺血发作", "TIA"),
        ("Seizure", "癫痫发作", ""),
        ("Epilepsy", "癫痫", ""),
        ("Alzheimer's Disease", "阿尔茨海默病", ""),
        ("Parkinson's Disease", "帕金森病", ""),
        ("Multiple Sclerosis", "多发性硬化", "MS"),
        ("Migraine", "偏头痛", ""),
        ("Tension Headache", "紧张性头痛", ""),
        ("Neuropathy", "神经病变", ""),
        ("Peripheral Neuropathy", "周围神经病变", ""),
        ("Spinal Cord", "脊髓", ""),
        ("Brain Tumor", "脑肿瘤", ""),
        ("Meningitis", "脑膜炎", ""),
        ("Encephalitis", "脑炎", ""),
        ("Cerebrospinal Fluid", "脑脊液", "CSF"),
        ("Dementia", "痴呆", ""),
        ("Cognitive Impairment", "认知障碍", ""),
        ("Motor Neuron", "运动神经元", ""),
        ("Autonomic Nervous System", "自主神经系统", ""),
        ("Central Nervous System", "中枢神经系统", "CNS"),
        ("Cerebellum", "小脑", ""),
        ("Cerebral Cortex", "大脑皮层", ""),
        ("Electroencephalography", "脑电图", "EEG"),
        ("Neurological Examination", "神经系统检查", ""),
        ("Intracranial Pressure", "颅内压", "ICP"),
        ("Nerve Conduction Study", "神经传导检查", ""),
    ],
    "呼吸系统": [
        ("Pulmonology", "呼吸病学", ""),
        ("Pneumonia", "肺炎", ""),
        ("Bronchitis", "支气管炎", ""),
        ("Asthma", "哮喘", ""),
        ("Chronic Obstructive Pulmonary Disease", "慢性阻塞性肺疾病", "COPD"),
        ("Emphysema", "肺气肿", ""),
        ("Pulmonary Fibrosis", "肺纤维化", ""),
        ("Tuberculosis", "肺结核", "TB"),
        ("Respiratory Failure", "呼吸衰竭", ""),
        ("Acute Respiratory Distress Syndrome", "急性呼吸窘迫综合征", "ARDS"),
        ("Pulmonary Edema", "肺水肿", ""),
        ("Pleural Effusion", "胸腔积液", ""),
        ("Bronchoscopy", "支气管镜检查", ""),
        ("Spirometry", "肺功能测定", ""),
        ("Oxygen Saturation", "血氧饱和度", ""),
        ("Mechanical Ventilation", "机械通气", ""),
        ("Intubation", "气管插管", ""),
        ("Pneumothorax", "气胸", ""),
        ("Sleep Apnea", "睡眠呼吸暂停", ""),
        ("Bronchodilator", "支气管扩张剂", ""),
        ("Expectorant", "祛痰药", ""),
        ("Respiratory Rate", "呼吸频率", ""),
        ("Oxygen Therapy", "氧疗", ""),
        ("Hemoptysis", "咯血", ""),
        ("Dyspnea", "呼吸困难", ""),
        ("Wheezing", "喘息", ""),
        ("Chest X-Ray", "胸部X线检查", ""),
        ("Artificial Respiration", "人工呼吸", ""),
    ],
    "消化系统": [
        ("Gastroenterology", "胃肠病学", ""),
        ("Gastroesophageal Reflux Disease", "胃食管反流病", "GERD"),
        ("Peptic Ulcer", "消化性溃疡", ""),
        ("Gastritis", "胃炎", ""),
        ("Hepatitis", "肝炎", ""),
        ("Cirrhosis", "肝硬化", ""),
        ("Inflammatory Bowel Disease", "炎症性肠病", "IBD"),
        ("Crohn's Disease", "克罗恩病", ""),
        ("Ulcerative Colitis", "溃疡性结肠炎", ""),
        ("Irritable Bowel Syndrome", "肠易激综合征", "IBS"),
        ("Pancreatitis", "胰腺炎", ""),
        ("Cholelithiasis", "胆结石", ""),
        ("Cholecystitis", "胆囊炎", ""),
        ("Appendicitis", "阑尾炎", ""),
        ("Endoscopy", "内镜检查", ""),
        ("Colonoscopy", "结肠镜检查", ""),
        ("Liver Function Test", "肝功能检查", ""),
        ("Jaundice", "黄疸", ""),
        ("Ascites", "腹水", ""),
        ("Peritonitis", "腹膜炎", ""),
        ("Celiac Disease", "乳糜泻", ""),
        ("Malabsorption", "吸收不良", ""),
        ("Constipation", "便秘", ""),
        ("Diarrhea", "腹泻", ""),
        ("Nausea", "恶心", ""),
        ("Vomiting", "呕吐", ""),
        ("Dysphagia", "吞咽困难", ""),
        ("Helicobacter pylori", "幽门螺杆菌", ""),
        ("Liver Transplant", "肝移植", ""),
    ],
    "内分泌与代谢": [
        ("Endocrinology", "内分泌学", ""),
        ("Diabetes Mellitus", "糖尿病", "DM"),
        ("Type 1 Diabetes", "1型糖尿病", ""),
        ("Type 2 Diabetes", "2型糖尿病", ""),
        ("Hypothyroidism", "甲状腺功能减退", ""),
        ("Hyperthyroidism", "甲状腺功能亢进", ""),
        ("Thyroiditis", "甲状腺炎", ""),
        ("Goiter", "甲状腺肿", ""),
        ("Addison's Disease", "艾迪生病", ""),
        ("Cushing's Syndrome", "库欣综合征", ""),
        ("Osteoporosis", "骨质疏松症", ""),
        ("Hyperlipidemia", "高脂血症", ""),
        ("Metabolic Syndrome", "代谢综合征", ""),
        ("Insulin Resistance", "胰岛素抵抗", ""),
        ("Glycated Hemoglobin", "糖化血红蛋白", "HbA1c"),
        ("Fasting Blood Glucose", "空腹血糖", "FBG"),
        ("Hypoglycemia", "低血糖", ""),
        ("Hyperglycemia", "高血糖", ""),
        ("Insulin", "胰岛素", ""),
        ("Metformin", "二甲双胍", ""),
        ("Thyroid-Stimulating Hormone", "促甲状腺激素", "TSH"),
        ("Cortisol", "皮质醇", ""),
        ("Testosterone", "睾酮", ""),
        ("Estrogen", "雌激素", ""),
        ("Prolactin", "催乳素", ""),
        ("Adrenal Gland", "肾上腺", ""),
        ("Pituitary Gland", "垂体", ""),
        ("Pancreas", "胰腺", ""),
        ("Thyroxine", "甲状腺素", "T4"),
    ],
    "感染与免疫": [
        ("Infectious Disease", "传染病", ""),
        ("Bacterium", "细菌", ""),
        ("Virus", "病毒", ""),
        ("Fungus", "真菌", ""),
        ("Parasite", "寄生虫", ""),
        ("Sepsis", "脓毒症", ""),
        ("Septic Shock", "脓毒性休克", ""),
        ("Antibiotic Resistance", "抗生素耐药", ""),
        ("Pathogen", "病原体", ""),
        ("Immune System", "免疫系统", ""),
        ("Immunity", "免疫", ""),
        ("Inflammation", "炎症", ""),
        ("Autoimmune Disease", "自身免疫性疾病", ""),
        ("Rheumatoid Arthritis", "类风湿关节炎", "RA"),
        ("Systemic Lupus Erythematosus", "系统性红斑狼疮", "SLE"),
        ("Immunodeficiency", "免疫缺陷", ""),
        ("Immunosuppression", "免疫抑制", ""),
        ("Antigen", "抗原", ""),
        ("Immunoglobulin", "免疫球蛋白", ""),
        ("Lymphocyte", "淋巴细胞", ""),
        ("B Cell", "B细胞", ""),
        ("T Cell", "T细胞", ""),
        ("Antiviral", "抗病毒药", ""),
        ("Antibiotic", "抗生素", ""),
        ("Antiseptic", "消毒剂", ""),
        ("Vaccination", "疫苗接种", ""),
        ("Herd Immunity", "群体免疫", ""),
        ("Immunocompromised", "免疫功能低下", ""),
        ("Opportunistic Infection", "机会性感染", ""),
    ],
    "影像学与检验": [
        ("Radiology", "放射学", ""),
        ("X-Ray", "X射线检查", ""),
        ("Computed Tomography", "计算机断层扫描", "CT"),
        ("Magnetic Resonance Imaging", "磁共振成像", "MRI"),
        ("Ultrasound", "超声检查", ""),
        ("Positron Emission Tomography", "正电子发射断层扫描", "PET"),
        ("Radiograph", "放射影像", ""),
        ("Contrast Agent", "造影剂", ""),
        ("Angiography", "血管造影", ""),
        ("Mammography", "乳腺X线摄影", ""),
        ("Fluoroscopy", "透视", ""),
        ("Nuclear Medicine", "核医学", ""),
        ("Histology", "组织学", ""),
        ("Cytology", "细胞学", ""),
        ("Complete Blood Count", "全血细胞计数", "CBC"),
        ("Urinalysis", "尿液分析", ""),
        ("Culture", "培养", ""),
        ("Sensitivity Test", "药敏试验", ""),
        ("Polymerase Chain Reaction", "聚合酶链反应", "PCR"),
        ("Biomarker", "生物标志物", ""),
        ("Specimen", "标本", ""),
        ("Centrifugation", "离心", ""),
        ("Microscope", "显微镜", ""),
        ("Tumor Marker", "肿瘤标志物", ""),
        ("Blood Glucose Test", "血糖检查", ""),
        ("Serum", "血清", ""),
        ("Plasma", "血浆", ""),
        ("Blood Cell Count", "血细胞计数", ""),
    ],
    "外科与麻醉": [
        ("Surgery", "手术", ""),
        ("Anesthesia", "麻醉", ""),
        ("Anesthesiology", "麻醉学", ""),
        ("General Anesthesia", "全身麻醉", ""),
        ("Local Anesthesia", "局部麻醉", ""),
        ("Regional Anesthesia", "区域麻醉", ""),
        ("Incision", "切口", ""),
        ("Suture", "缝合", ""),
        ("Wound", "伤口", ""),
        ("Hemorrhage", "出血", ""),
        ("Hemostasis", "止血", ""),
        ("Blood Transfusion", "输血", ""),
        ("Blood Loss", "失血", ""),
        ("Operating Room", "手术室", ""),
        ("Preoperative", "术前", ""),
        ("Postoperative", "术后", ""),
        ("Intraoperative", "术中", ""),
        ("Wound Infection", "伤口感染", ""),
        ("Scar", "瘢痕", ""),
        ("Organ Transplant", "器官移植", ""),
        ("Graft", "移植物", ""),
        ("Donor", "供体", ""),
        ("Recipient", "受体", ""),
        ("Laparoscopy", "腹腔镜手术", ""),
        ("Minimally Invasive Surgery", "微创手术", ""),
        ("Amputation", "截肢", ""),
        ("Fracture Reduction", "骨折复位", ""),
        ("Emergency Surgery", "急诊手术", ""),
        ("Surgical Resection", "手术切除", ""),
        ("Wound Healing", "伤口愈合", ""),
    ],
    "儿科与妇产": [
        ("Pediatrics", "儿科学", ""),
        ("Obstetrics", "产科学", ""),
        ("Gynecology", "妇科学", ""),
        ("Pregnancy", "妊娠", ""),
        ("Delivery", "分娩", ""),
        ("Cesarean Section", "剖宫产", ""),
        ("Fetus", "胎儿", ""),
        ("Neonate", "新生儿", ""),
        ("Premature Infant", "早产儿", ""),
        ("Gestational Age", "胎龄", ""),
        ("Labor", "分娩", ""),
        ("Uterine Contraction", "宫缩", ""),
        ("Placenta", "胎盘", ""),
        ("Umbilical Cord", "脐带", ""),
        ("Amniotic Fluid", "羊水", ""),
        ("Prenatal Care", "产前检查", ""),
        ("Postpartum", "产后", ""),
        ("Miscarriage", "流产", ""),
        ("Ectopic Pregnancy", "异位妊娠", ""),
        ("Preeclampsia", "子痫前期", ""),
        ("Gestational Diabetes", "妊娠期糖尿病", ""),
        ("Menstruation", "月经", ""),
        ("Menopause", "绝经", ""),
        ("Uterus", "子宫", ""),
        ("Ovary", "卵巢", ""),
        ("Fallopian Tube", "输卵管", ""),
        ("Cervix", "宫颈", ""),
        ("Human Papillomavirus", "人乳头瘤病毒", "HPV"),
        ("Breastfeeding", "母乳喂养", ""),
        ("Growth and Development", "生长发育", ""),
    ],
    "精神科与心理": [
        ("Psychiatry", "精神病学", ""),
        ("Depression", "抑郁症", ""),
        ("Anxiety Disorder", "焦虑障碍", ""),
        ("Panic Disorder", "惊恐障碍", ""),
        ("Bipolar Disorder", "双相情感障碍", ""),
        ("Schizophrenia", "精神分裂症", ""),
        ("Obsessive-Compulsive Disorder", "强迫症", "OCD"),
        ("Post-Traumatic Stress Disorder", "创伤后应激障碍", "PTSD"),
        ("Attention Deficit Hyperactivity Disorder", "注意缺陷多动障碍", "ADHD"),
        ("Autism Spectrum Disorder", "自闭症谱系障碍", "ASD"),
        ("Insomnia", "失眠", ""),
        ("Psychotherapy", "心理治疗", ""),
        ("Cognitive Behavioral Therapy", "认知行为疗法", "CBT"),
        ("Antidepressant", "抗抑郁药", ""),
        ("Antipsychotic", "抗精神病药", ""),
        ("Mood Disorder", "心境障碍", ""),
        ("Personality Disorder", "人格障碍", ""),
        ("Psychosis", "精神病性障碍", ""),
        ("Delusion", "妄想", ""),
        ("Hallucination", "幻觉", ""),
        ("Suicide", "自杀", ""),
        ("Self-Harm", "自伤", ""),
        ("Mental Health", "心理健康", ""),
        ("Psychotropic Drug", "精神药物", ""),
        ("Benzodiazepine", "苯二氮卓类药物", ""),
        ("Behavioral Therapy", "行为治疗", ""),
        ("Emotional Distress", "情绪困扰", ""),
    ],
    "公共卫生": [
        ("Public Health", "公共卫生", ""),
        ("Incidence", "发病率", ""),
        ("Prevalence", "患病率", ""),
        ("Outbreak", "暴发", ""),
        ("Pandemic", "大流行", ""),
        ("Epidemic", "流行", ""),
        ("Endemic", "地方性流行", ""),
        ("Quarantine", "隔离", ""),
        ("Screening", "筛查", ""),
        ("Prevention", "预防", ""),
        ("Health Promotion", "健康促进", ""),
        ("Health Policy", "卫生政策", ""),
        ("Health Insurance", "医疗保险", ""),
        ("Vaccination Coverage", "疫苗接种覆盖率", ""),
        ("Disease Surveillance", "疾病监测", ""),
        ("Contact Tracing", "接触者追踪", ""),
        ("Risk Factor", "危险因素", ""),
        ("Protective Factor", "保护因素", ""),
        ("Mortality Rate", "死亡率", ""),
        ("Life Expectancy", "预期寿命", ""),
        ("Infant Mortality", "婴儿死亡率", ""),
        ("Maternal Mortality", "孕产妇死亡率", ""),
        ("Environmental Health", "环境卫生", ""),
        ("Health Education", "健康教育", ""),
        ("Disease Prevention", "疾病预防", ""),
        ("Health Disparity", "健康差异", ""),
    ],
}


# ==================== 金融/经济学 术语库 ====================
FINANCE_GLOSSARY = {
    "金融基础": [
        ("Asset", "资产", ""),
        ("Liability", "负债", ""),
        ("Equity", "权益", ""),
        ("Revenue", "收入", ""),
        ("Expense", "费用", ""),
        ("Profit", "利润", ""),
        ("Loss", "亏损", ""),
        ("Margin", "利润率", ""),
        ("Dividend", "股息", ""),
        ("Yield", "收益率", ""),
        ("Return on Investment", "投资回报率", "ROI"),
        ("Net Present Value", "净现值", "NPV"),
        ("Internal Rate of Return", "内部收益率", "IRR"),
        ("Earnings Per Share", "每股收益", "EPS"),
        ("Price-Earnings Ratio", "市盈率", "P/E"),
        ("Book Value", "账面价值", ""),
        ("Market Capitalization", "市值", ""),
        ("Enterprise Value", "企业价值", "EV"),
        ("EBITDA", "息税折旧摊销前利润", "EBITDA"),
        ("Free Cash Flow", "自由现金流", "FCF"),
        ("Working Capital", "营运资本", ""),
        ("Debt-to-Equity Ratio", "负债权益比", "D/E"),
        ("Current Ratio", "流动比率", ""),
        ("Quick Ratio", "速动比率", ""),
    ],
    "投资与市场": [
        ("Stock", "股票", ""),
        ("Bond", "债券", ""),
        ("Security", "证券", ""),
        ("Derivative", "衍生品", ""),
        ("Option", "期权", ""),
        ("Futures", "期货", ""),
        ("Swap", "互换", ""),
        ("Forward Contract", "远期合约", ""),
        ("Initial Public Offering", "首次公开发行", "IPO"),
        ("Secondary Offering", "增发", ""),
        ("Diversification", "分散投资", ""),
        ("Hedge", "对冲", ""),
        ("Arbitrage", "套利", ""),
        ("Bull Market", "牛市", ""),
        ("Bear Market", "熊市", ""),
        ("Volatility", "波动率", ""),
        ("Liquidity", "流动性", ""),
        ("Benchmark", "基准", ""),
        ("Index Fund", "指数基金", ""),
        ("Exchange-Traded Fund", "交易所交易基金", "ETF"),
        ("Mutual Fund", "共同基金", ""),
        ("Hedge Fund", "对冲基金", ""),
        ("Private Equity", "私募股权", ""),
        ("Venture Capital", "风险投资", ""),
        ("Angel Investor", "天使投资人", ""),
    ],
    "经济与政策": [
        ("Gross Domestic Product", "国内生产总值", "GDP"),
        ("Consumer Price Index", "消费者价格指数", "CPI"),
        ("Purchasing Power Parity", "购买力平价", "PPP"),
        ("Inflation", "通货膨胀", ""),
        ("Deflation", "通货紧缩", ""),
        ("Stagflation", "滞胀", ""),
        ("Recession", "衰退", ""),
        ("Fiscal Policy", "财政政策", ""),
        ("Monetary Policy", "货币政策", ""),
        ("Interest Rate", "利率", ""),
        ("Exchange Rate", "汇率", ""),
        ("Balance of Trade", "贸易差额", ""),
        ("Current Account", "经常账户", ""),
        ("Sovereign Debt", "主权债务", ""),
        ("Quantitative Easing", "量化宽松", ""),
        ("Supply and Demand", "供给与需求", ""),
        ("Elasticity", "弹性", ""),
        ("Opportunity Cost", "机会成本", ""),
        ("Marginal Utility", "边际效用", ""),
        ("Comparative Advantage", "比较优势", ""),
        ("Free Trade", "自由贸易", ""),
        ("Tariff", "关税", ""),
        ("Subsidy", "补贴", ""),
        ("Market Failure", "市场失灵", ""),
        ("Externalities", "外部性", ""),
    ],
    "公司金融": [
        ("Corporate Finance", "公司金融", ""),
        ("Capital Structure", "资本结构", ""),
        ("Cost of Capital", "资本成本", ""),
        ("Weighted Average Cost of Capital", "加权平均资本成本", "WACC"),
        ("Capital Budgeting", "资本预算", ""),
        ("Merger and Acquisition", "并购", "M&A"),
        ("Leveraged Buyout", "杠杆收购", "LBO"),
        ("Management Buyout", "管理层收购", "MBO"),
        ("Debt Financing", "债务融资", ""),
        ("Equity Financing", "股权融资", ""),
        ("Convertible Bond", "可转换债券", ""),
        ("Preferred Stock", "优先股", ""),
        ("Common Stock", "普通股", ""),
        ("Share Buyback", "股票回购", ""),
        ("Stock Split", "股票分割", ""),
        ("Spin-Off", "分拆", ""),
        ("Conglomerate", "企业集团", ""),
        ("Synergy", "协同效应", ""),
        ("Due Diligence", "尽职调查", ""),
        ("Valuation", "估值", ""),
        ("Discounted Cash Flow", "现金流折现", "DCF"),
        ("Cash Flow Statement", "现金流量表", ""),
        ("Balance Sheet", "资产负债表", ""),
        ("Income Statement", "利润表", ""),
        ("Financial Leverage", "财务杠杆", ""),
        ("Bankruptcy", "破产", ""),
        ("Restructuring", "重组", ""),
        ("Dividend Payout", "股利支付", ""),
        ("Shareholder", "股东", ""),
        ("Corporate Governance", "公司治理", ""),
    ],
    "银行业": [
        ("Commercial Bank", "商业银行", ""),
        ("Central Bank", "中央银行", ""),
        ("Retail Banking", "零售银行", ""),
        ("Investment Banking", "投资银行", ""),
        ("Corporate Banking", "公司银行业务", ""),
        ("Deposit", "存款", ""),
        ("Withdrawal", "取款", ""),
        ("Loan", "贷款", ""),
        ("Mortgage", "抵押贷款", ""),
        ("Collateral", "抵押品", ""),
        ("Interest", "利息", ""),
        ("Principal", "本金", ""),
        ("Credit", "信贷", ""),
        ("Credit Risk", "信用风险", ""),
        ("Default", "违约", ""),
        ("Non-Performing Loan", "不良贷款", "NPL"),
        ("Reserve Requirement", "法定准备金率", ""),
        ("Liquidity", "流动性", ""),
        ("Lender of Last Resort", "最后贷款人", ""),
        ("Overdraft", "透支", ""),
        ("Letter of Credit", "信用证", "L/C"),
        ("Wire Transfer", "电汇", ""),
        ("Electronic Funds Transfer", "电子资金转账", "EFT"),
        ("Financial Intermediary", "金融中介", ""),
        ("Net Interest Margin", "净息差", "NIM"),
        ("Capital Adequacy Ratio", "资本充足率", "CAR"),
        ("Basel Accord", "巴塞尔协议", ""),
        ("Payment System", "支付系统", ""),
        ("Clearing and Settlement", "清算与结算", ""),
    ],
    "保险与精算": [
        ("Insurance", "保险", ""),
        ("Insurer", "保险人", ""),
        ("Policyholder", "投保人", ""),
        ("Premium", "保费", ""),
        ("Coverage", "保险范围", ""),
        ("Claim", "理赔", ""),
        ("Deductible", "免赔额", ""),
        ("Coinsurance", "共保", ""),
        ("Policy", "保单", ""),
        ("Beneficiary", "受益人", ""),
        ("Underwriting", "承保", ""),
        ("Actuary", "精算师", ""),
        ("Actuarial Science", "精算学", ""),
        ("Life Insurance", "人寿保险", ""),
        ("Health Insurance", "健康保险", ""),
        ("Property Insurance", "财产保险", ""),
        ("Liability Insurance", "责任保险", ""),
        ("Reinsurance", "再保险", ""),
        ("Annuity", "年金", ""),
        ("Pension", "养老金", ""),
        ("Mortality Table", "死亡率表", ""),
        ("Risk Pooling", "风险共担", ""),
        ("Moral Hazard", "道德风险", ""),
        ("Adverse Selection", "逆向选择", ""),
        ("Loss Ratio", "赔付率", ""),
        ("Expense Ratio", "费用率", ""),
        ("Insurance Claim", "保险索赔", ""),
        ("Term Life Insurance", "定期寿险", ""),
        ("Whole Life Insurance", "终身寿险", ""),
    ],
    "风险管理": [
        ("Risk Management", "风险管理", ""),
        ("Market Risk", "市场风险", ""),
        ("Operational Risk", "操作风险", ""),
        ("Liquidity Risk", "流动性风险", ""),
        ("Interest Rate Risk", "利率风险", ""),
        ("Currency Risk", "汇率风险", ""),
        ("Systemic Risk", "系统性风险", ""),
        ("Idiosyncratic Risk", "非系统性风险", ""),
        ("Value at Risk", "风险价值", "VaR"),
        ("Stress Test", "压力测试", ""),
        ("Scenario Analysis", "情景分析", ""),
        ("Sensitivity Analysis", "敏感性分析", ""),
        ("Risk Appetite", "风险偏好", ""),
        ("Risk Tolerance", "风险承受能力", ""),
        ("Risk Exposure", "风险敞口", ""),
        ("Hedging", "对冲", ""),
        ("Derivatives", "衍生品", ""),
        ("Credit Default Swap", "信用违约互换", "CDS"),
        ("Risk Premium", "风险溢价", ""),
        ("Diversification", "分散化", ""),
        ("Correlation", "相关性", ""),
        ("Volatility", "波动率", ""),
        ("Standard Deviation", "标准差", ""),
        ("Beta Coefficient", "贝塔系数", ""),
        ("Alpha", "阿尔法收益", ""),
        ("Sharpe Ratio", "夏普比率", ""),
        ("Risk-Adjusted Return", "风险调整后收益", ""),
    ],
    "会计与审计": [
        ("Accounting", "会计", ""),
        ("Financial Accounting", "财务会计", ""),
        ("Managerial Accounting", "管理会计", ""),
        ("Auditing", "审计", ""),
        ("Auditor", "审计师", ""),
        ("Internal Audit", "内部审计", ""),
        ("External Audit", "外部审计", ""),
        ("Accrual Accounting", "权责发生制", ""),
        ("Cash Basis Accounting", "收付实现制", ""),
        ("Double-Entry Bookkeeping", "复式记账", ""),
        ("General Ledger", "总账", ""),
        ("Trial Balance", "试算平衡表", ""),
        ("Account Receivable", "应收账款", "AR"),
        ("Account Payable", "应付账款", "AP"),
        ("Inventory", "存货", ""),
        ("Fixed Asset", "固定资产", ""),
        ("Intangible Asset", "无形资产", ""),
        ("Amortization", "摊销", ""),
        ("Depreciation", "折旧", ""),
        ("Goodwill", "商誉", ""),
        ("Impairment", "减值", ""),
        ("Consolidated Financial Statement", "合并财务报表", ""),
        ("Audit Report", "审计报告", ""),
        ("Internal Control", "内部控制", ""),
        ("Fraud", "舞弊", ""),
        ("Materiality", "重要性", ""),
        ("Accrual", "应计项目", ""),
        ("Deferred Revenue", "递延收入", ""),
    ],
    "国际金融": [
        ("International Finance", "国际金融", ""),
        ("Foreign Exchange Market", "外汇市场", "FX"),
        ("Exchange Rate", "汇率", ""),
        ("Spot Exchange Rate", "即期汇率", ""),
        ("Forward Exchange Rate", "远期汇率", ""),
        ("Appreciation", "升值", ""),
        ("Depreciation", "贬值", ""),
        ("Currency Peg", "货币挂钩", ""),
        ("Floating Exchange Rate", "浮动汇率", ""),
        ("Fixed Exchange Rate", "固定汇率", ""),
        ("Balance of Payments", "国际收支", ""),
        ("Current Account", "经常账户", ""),
        ("Capital Account", "资本账户", ""),
        ("Foreign Direct Investment", "外商直接投资", "FDI"),
        ("Portfolio Investment", "证券投资", ""),
        ("International Monetary Fund", "国际货币基金组织", "IMF"),
        ("World Bank", "世界银行", ""),
        ("Sovereign Wealth Fund", "主权财富基金", ""),
        ("Remittance", "侨汇", ""),
        ("Cross-Border Transaction", "跨境交易", ""),
        ("Offshore Financial Center", "离岸金融中心", ""),
        ("Currency Swap", "货币互换", ""),
        ("Foreign Exchange Reserve", "外汇储备", ""),
        ("Trade Surplus", "贸易顺差", ""),
        ("Trade Deficit", "贸易逆差", ""),
    ],
    "衍生品与量化": [
        ("Derivative", "衍生品", ""),
        ("Options Contract", "期权合约", ""),
        ("Call Option", "看涨期权", ""),
        ("Put Option", "看跌期权", ""),
        ("Strike Price", "行权价", ""),
        ("Expiration Date", "到期日", ""),
        ("Underlying Asset", "标的资产", ""),
        ("Futures Contract", "期货合约", ""),
        ("Forward Contract", "远期合约", ""),
        ("Swap Contract", "互换合约", ""),
        ("Quantitative Finance", "量化金融", ""),
        ("Quantitative Analysis", "量化分析", ""),
        ("Algorithmic Trading", "算法交易", ""),
        ("High-Frequency Trading", "高频交易", "HFT"),
        ("Backtesting", "回测", ""),
        ("Black-Scholes Model", "布莱克-舒尔斯模型", ""),
        ("Monte Carlo Simulation", "蒙特卡洛模拟", ""),
        ("Arbitrage Pricing Theory", "套利定价理论", "APT"),
        ("Geometric Brownian Motion", "几何布朗运动", ""),
        ("Martingale", "鞅", ""),
        ("Stochastic Process", "随机过程", ""),
        ("Mean Reversion", "均值回归", ""),
        ("Cointegration", "协整", ""),
        ("Volatility Smile", "波动率微笑", ""),
        ("Greeks", "希腊字母指标", ""),
        ("Delta Hedging", "德尔塔对冲", ""),
        ("Program Trading", "程序化交易", ""),
        ("Market Maker", "做市商", ""),
    ],
    "私募股权与风投": [
        ("Private Equity", "私募股权", "PE"),
        ("Venture Capital", "风险投资", "VC"),
        ("Angel Investment", "天使投资", ""),
        ("Seed Funding", "种子轮融资", ""),
        ("Series A Funding", "A轮融资", ""),
        ("Startup", "初创企业", ""),
        ("Entrepreneur", "企业家", ""),
        ("Exit Strategy", "退出策略", ""),
        ("Initial Public Offering", "首次公开发行", "IPO"),
        ("Acquisition", "收购", ""),
        ("Term Sheet", "投资条款清单", ""),
        ("Valuation Cap", "估值上限", ""),
        ("Equity Stake", "股权", ""),
        ("Founder", "创始人", ""),
        ("Board of Directors", "董事会", ""),
        ("Due Diligence", "尽职调查", ""),
        ("Unicorn", "独角兽公司", ""),
        ("Growth Capital", "成长资本", ""),
        ("Secondary Market", "二级市场", ""),
        ("Fund Manager", "基金管理人", ""),
        ("Limited Partner", "有限合伙人", "LP"),
        ("General Partner", "普通合伙人", "GP"),
        ("Carried Interest", "附带权益", ""),
        ("Fundraising", "募资", ""),
        ("Due Diligence Report", "尽职调查报告", ""),
    ],
    "个人理财": [
        ("Personal Finance", "个人理财", ""),
        ("Budget", "预算", ""),
        ("Savings", "储蓄", ""),
        ("Savings Account", "储蓄账户", ""),
        ("Checking Account", "活期账户", ""),
        ("Certificate of Deposit", "定期存单", "CD"),
        ("Retirement Planning", "退休规划", ""),
        ("401(k) Plan", "401(k)退休计划", ""),
        ("Individual Retirement Account", "个人退休账户", "IRA"),
        ("Credit Score", "信用评分", ""),
        ("Credit Card", "信用卡", ""),
        ("Debt Management", "债务管理", ""),
        ("Financial Planning", "财务规划", ""),
        ("Wealth Management", "财富管理", ""),
        ("Net Worth", "净资产", ""),
        ("Emergency Fund", "应急基金", ""),
        ("Insurance Premium", "保险费", ""),
        ("Tax Planning", "税务规划", ""),
        ("Estate Planning", "遗产规划", ""),
        ("Will", "遗嘱", ""),
        ("Trust", "信托", ""),
        ("Compound Interest", "复利", ""),
        ("Simple Interest", "单利", ""),
        ("Financial Advisor", "理财顾问", ""),
        ("Asset Allocation", "资产配置", ""),
        ("Liability Management", "负债管理", ""),
    ],
}


# ==================== 法律/法规 术语库 ====================
LEGAL_GLOSSARY = {
    "法律通用": [
        ("Statute", "法规", ""),
        ("Regulation", "条例", ""),
        ("Legislation", "立法", ""),
        ("Jurisdiction", "管辖权", ""),
        ("Plaintiff", "原告", ""),
        ("Defendant", "被告", ""),
        ("Litigation", "诉讼", ""),
        ("Arbitration", "仲裁", ""),
        ("Mediation", "调解", ""),
        ("Contract", "合同", ""),
        ("Agreement", "协议", ""),
        ("Breach of Contract", "违约", ""),
        ("Damages", "损害赔偿", ""),
        ("Indemnity", "赔偿", ""),
        ("Liability", "责任", ""),
        ("Negligence", "过失", ""),
        ("Tort", "侵权", ""),
        ("Remedy", "救济", ""),
        ("Intellectual Property", "知识产权", ""),
        ("Patent", "专利", ""),
        ("Copyright", "版权", ""),
        ("Trademark", "商标", ""),
        ("Trade Secret", "商业秘密", ""),
        ("Compliance", "合规", ""),
        ("Due Diligence", "尽职调查", ""),
        ("Force Majeure", "不可抗力", ""),
        ("Confidentiality", "保密", ""),
        ("Non-Disclosure Agreement", "保密协议", "NDA"),
        ("Memorandum of Understanding", "谅解备忘录", "MOU"),
        ("Terms and Conditions", "条款与条件", ""),
    ],
    "合同法": [
        ("Contract Law", "合同法", ""),
        ("Offer", "要约", ""),
        ("Acceptance", "承诺", ""),
        ("Consideration", "对价", ""),
        ("Contractual Capacity", "缔约能力", ""),
        ("Contract Formation", "合同成立", ""),
        ("Contract Performance", "合同履行", ""),
        ("Contract Termination", "合同终止", ""),
        ("Contract Rescission", "合同解除", ""),
        ("Contract Amendment", "合同变更", ""),
        ("Warranty", "保证", ""),
        ("Representation", "陈述", ""),
        ("Covenant", "契约义务", ""),
        ("Liquidated Damages", "违约金", ""),
        ("Penalty Clause", "罚则条款", ""),
        ("Breach of Warranty", "违反保证", ""),
        ("Fundamental Breach", "根本违约", ""),
        ("Anticipatory Breach", "预期违约", ""),
        ("Contractual Obligation", "合同义务", ""),
        ("Contractual Right", "合同权利", ""),
        ("Offer and Acceptance", "要约与承诺", ""),
        ("Letter of Intent", "意向书", "LOI"),
        ("Master Agreement", "主协议", ""),
        ("Exclusive Agreement", "排他性协议", ""),
        ("Renewal", "续约", ""),
        ("Termination Clause", "终止条款", ""),
        ("Governing Law", "适用法律", ""),
        ("Dispute Resolution", "争议解决", ""),
        ("Waiver", "放弃权利", ""),
        ("Severability", "可分性条款", ""),
    ],
    "公司法": [
        ("Company Law", "公司法", ""),
        ("Corporation", "公司", ""),
        ("Limited Liability Company", "有限责任公司", "LLC"),
        ("Joint Stock Company", "股份公司", ""),
        ("Shareholder", "股东", ""),
        ("Board of Directors", "董事会", ""),
        ("Executive Officer", "高管", ""),
        ("Chief Executive Officer", "首席执行官", "CEO"),
        ("Chief Financial Officer", "首席财务官", "CFO"),
        ("Corporate Veil", "公司面纱", ""),
        ("Articles of Incorporation", "公司章程", ""),
        ("Bylaws", "公司内部规章", ""),
        ("Share Capital", "股本", ""),
        ("Registered Capital", "注册资本", ""),
        ("Dividend", "股息", ""),
        ("Voting Right", "表决权", ""),
        ("Proxy", "代理投票", ""),
        ("Fiduciary Duty", "信托义务", ""),
        ("Duty of Loyalty", "忠实义务", ""),
        ("Duty of Care", "注意义务", ""),
        ("Derivative Action", "股东代表诉讼", ""),
        ("Piercing the Corporate Veil", "刺破公司面纱", ""),
        ("Dissolution", "解散", ""),
        ("Liquidation", "清算", ""),
        ("Insolvency", "资不抵债", ""),
        ("Annual General Meeting", "年度股东大会", "AGM"),
        ("Special Resolution", "特别决议", ""),
        ("Ordinary Resolution", "普通决议", ""),
        ("Subsidiary", "子公司", ""),
        ("Holding Company", "控股公司", ""),
    ],
    "刑法": [
        ("Criminal Law", "刑法", ""),
        ("Crime", "犯罪", ""),
        ("Offense", "违法行为", ""),
        ("Felony", "重罪", ""),
        ("Misdemeanor", "轻罪", ""),
        ("Indictment", "起诉", ""),
        ("Prosecution", "公诉", ""),
        ("Prosecutor", "检察官", ""),
        ("Criminal Defendant", "刑事被告", ""),
        ("Criminal Liability", "刑事责任", ""),
        ("Criminal Intent", "犯罪故意", ""),
        ("Negligence", "过失", ""),
        ("Mens Rea", "犯罪意图", ""),
        ("Actus Reus", "犯罪行为", ""),
        ("Attempt", "犯罪未遂", ""),
        ("Conspiracy", "共谋", ""),
        ("Accomplice", "共犯", ""),
        ("Accessory", "从犯", ""),
        ("Principal Offender", "主犯", ""),
        ("Self-Defense", "正当防卫", ""),
        ("Sentence", "量刑", ""),
        ("Imprisonment", "监禁", ""),
        ("Probation", "缓刑", ""),
        ("Parole", "假释", ""),
        ("Bail", "保释", ""),
        ("Acquittal", "无罪释放", ""),
        ("Conviction", "定罪", ""),
        ("Appeal", "上诉", ""),
        ("Statute of Limitations", "诉讼时效", ""),
        ("Criminal Procedure", "刑事诉讼程序", ""),
    ],
    "行政法": [
        ("Administrative Law", "行政法", ""),
        ("Administrative Agency", "行政机关", ""),
        ("Administrative Regulation", "行政法规", ""),
        ("Executive Order", "行政命令", ""),
        ("Administrative Decision", "行政决定", ""),
        ("Administrative Review", "行政复议", ""),
        ("Judicial Review", "司法审查", ""),
        ("Administrative Procedure", "行政程序", ""),
        ("Administrative Penalty", "行政处罚", ""),
        ("Administrative License", "行政许可", ""),
        ("Administrative Litigation", "行政诉讼", ""),
        ("Government Agency", "政府机构", ""),
        ("Public Official", "公职人员", ""),
        ("Freedom of Information", "信息自由", ""),
        ("Public Records", "公共记录", ""),
        ("Regulatory Agency", "监管机构", ""),
        ("Rulemaking", "规则制定", ""),
        ("Enforcement Action", "执法行动", ""),
        ("Administrative Order", "行政令", ""),
        ("Adjudication", "行政裁决", ""),
        ("Notice and Comment", "通知与评议", ""),
        ("Delegation of Authority", "权力委托", ""),
        ("Separation of Powers", "权力分立", ""),
        ("Administrative Discretion", "行政裁量", ""),
        ("Due Process", "正当程序", ""),
    ],
    "知识产权法": [
        ("Intellectual Property Law", "知识产权法", "IP"),
        ("Patent Law", "专利法", ""),
        ("Patent Application", "专利申请", ""),
        ("Patent Infringement", "专利侵权", ""),
        ("Patentability", "可专利性", ""),
        ("Novelty", "新颖性", ""),
        ("Inventive Step", "创造性步骤", ""),
        ("Industrial Applicability", "工业实用性", ""),
        ("Copyright Law", "著作权法", ""),
        ("Copyright Infringement", "版权侵权", ""),
        ("Fair Use", "合理使用", ""),
        ("Public Domain", "公有领域", ""),
        ("Moral Rights", "精神权利", ""),
        ("Trademark Law", "商标法", ""),
        ("Trademark Registration", "商标注册", ""),
        ("Trademark Infringement", "商标侵权", ""),
        ("Distinctiveness", "显著性", ""),
        ("Likelihood of Confusion", "混淆可能性", ""),
        ("Industrial Design", "工业设计", ""),
        ("Geographical Indication", "地理标志", "GI"),
        ("Trade Secret Protection", "商业秘密保护", ""),
        ("Licensing Agreement", "许可协议", ""),
        ("Royalty", "版税", ""),
        ("Prior Art", "现有技术", ""),
        ("Patent Cooperation Treaty", "专利合作条约", "PCT"),
        ("World Intellectual Property Organization", "世界知识产权组织", "WIPO"),
        ("Compulsory License", "强制许可", ""),
        ("Trademark Dilution", "商标淡化", ""),
    ],
    "劳动法": [
        ("Labor Law", "劳动法", ""),
        ("Employment Contract", "劳动合同", ""),
        ("Employer", "雇主", ""),
        ("Employee", "雇员", ""),
        ("Labor Relations", "劳动关系", ""),
        ("Collective Bargaining", "集体谈判", ""),
        ("Labor Union", "工会", ""),
        ("Minimum Wage", "最低工资", ""),
        ("Overtime Pay", "加班费", ""),
        ("Working Hours", "工作时间", ""),
        ("Workplace Safety", "工作场所安全", ""),
        ("Occupational Injury", "工伤", ""),
        ("Workers' Compensation", "工伤赔偿", ""),
        ("Discrimination", "歧视", ""),
        ("Harassment", "骚扰", ""),
        ("Wrongful Termination", "非法解雇", ""),
        ("Unfair Dismissal", "不公平解雇", ""),
        ("Notice Period", "通知期", ""),
        ("Severance Pay", "遣散费", ""),
        ("Paid Leave", "带薪休假", ""),
        ("Sick Leave", "病假", ""),
        ("Maternity Leave", "产假", ""),
        ("Paternity Leave", "陪产假", ""),
        ("Employment Tribunal", "劳动法庭", ""),
        ("Trade Union", "工会组织", ""),
        ("Equal Employment Opportunity", "平等就业机会", "EEO"),
        ("Labor Dispute", "劳动争议", ""),
        ("Social Security", "社会保障", ""),
    ],
    "国际法": [
        ("International Law", "国际法", ""),
        ("Treaty", "条约", ""),
        ("Convention", "公约", ""),
        ("Protocol", "议定书", ""),
        ("Sovereignty", "主权", ""),
        ("Diplomatic Immunity", "外交豁免", ""),
        ("Extradition", "引渡", ""),
        ("Asylum", "庇护", ""),
        ("International Court of Justice", "国际法院", "ICJ"),
        ("United Nations", "联合国", "UN"),
        ("Security Council", "安全理事会", ""),
        ("International Criminal Court", "国际刑事法院", "ICC"),
        ("War Crime", "战争罪", ""),
        ("Crimes Against Humanity", "危害人类罪", ""),
        ("Genocide", "种族灭绝", ""),
        ("Humanitarian Law", "人道主义法", ""),
        ("Geneva Convention", "日内瓦公约", ""),
        ("Ratification", "批准", ""),
        ("Accession", "加入", ""),
        ("Reservation", "保留条款", ""),
        ("Customary International Law", "国际习惯法", ""),
        ("Jurisdiction", "管辖权", ""),
        ("Territorial Waters", "领海", ""),
        ("Exclusive Economic Zone", "专属经济区", "EEZ"),
        ("Diplomatic Relations", "外交关系", ""),
        ("Sanctions", "制裁", ""),
        ("Embargo", "禁运", ""),
        ("State Sovereignty", "国家主权", ""),
    ],
    "诉讼与证据": [
        ("Litigation", "诉讼", ""),
        ("Civil Procedure", "民事诉讼程序", ""),
        ("Complaint", "起诉状", ""),
        ("Answer", "答辩状", ""),
        ("Counterclaim", "反诉", ""),
        ("Cross-Examination", "交叉询问", ""),
        ("Direct Examination", "直接询问", ""),
        ("Hearing", "听证", ""),
        ("Trial", "审判", ""),
        ("Jury", "陪审团", ""),
        ("Verdict", "裁决", ""),
        ("Judgment", "判决", ""),
        ("Burden of Proof", "举证责任", ""),
        ("Preponderance of Evidence", "优势证据", ""),
        ("Beyond Reasonable Doubt", "排除合理怀疑", ""),
        ("Evidence", "证据", ""),
        ("Admissible Evidence", "可采纳证据", ""),
        ("Hearsay", "传闻证据", ""),
        ("Documentary Evidence", "书面证据", ""),
        ("Witness", "证人", ""),
        ("Expert Witness", "专家证人", ""),
        ("Deposition", "证词笔录", ""),
        ("Subpoena", "传票", ""),
        ("Discovery", "证据开示", ""),
        ("Motion", "动议", ""),
        ("Summary Judgment", "简易判决", ""),
        ("Appellate Court", "上诉法院", ""),
        ("Court of First Instance", "一审法院", ""),
        ("Statute of Limitations", "诉讼时效", ""),
        ("Standing", "诉讼主体资格", ""),
    ],
    "仲裁与争议解决": [
        ("Arbitration", "仲裁", ""),
        ("Mediation", "调解", ""),
        ("Conciliation", "和解", ""),
        ("Negotiation", "协商", ""),
        ("Arbitral Tribunal", "仲裁庭", ""),
        ("Arbitration Clause", "仲裁条款", ""),
        ("Arbitration Award", "仲裁裁决", ""),
        ("Enforcement of Award", "裁决执行", ""),
        ("International Arbitration", "国际仲裁", ""),
        ("Alternative Dispute Resolution", "替代性争议解决", "ADR"),
        ("Arbitrator", "仲裁员", ""),
        ("Mediator", "调解员", ""),
        ("Settlement Agreement", "和解协议", ""),
        ("Dispute", "争议", ""),
        ("Claimant", "申请人", ""),
        ("Respondent", "被申请人", ""),
        ("Interim Measure", "临时措施", ""),
        ("Seat of Arbitration", "仲裁地", ""),
        ("Governing Rules", "适用规则", ""),
        ("Enforcement Order", "执行令", ""),
        ("Binding Award", "终局裁决", ""),
        ("UNCITRAL", "联合国国际贸易法委员会", "UNCITRAL"),
        ("Preliminary Hearing", "初步听证", ""),
        ("Confidentiality in Arbitration", "仲裁保密", ""),
    ],
    "税法": [
        ("Tax Law", "税法", ""),
        ("Taxation", "征税", ""),
        ("Taxpayer", "纳税人", ""),
        ("Income Tax", "所得税", ""),
        ("Corporate Tax", "公司税", ""),
        ("Value-Added Tax", "增值税", "VAT"),
        ("Withholding Tax", "预扣税", ""),
        ("Capital Gains Tax", "资本利得税", ""),
        ("Property Tax", "财产税", ""),
        ("Excise Tax", "消费税", ""),
        ("Customs Duty", "关税", ""),
        ("Tax Evasion", "逃税", ""),
        ("Tax Avoidance", "避税", ""),
        ("Tax Deduction", "税收扣除", ""),
        ("Tax Credit", "税收抵免", ""),
        ("Tax Exemption", "免税", ""),
        ("Tax Haven", "避税天堂", ""),
        ("Double Taxation", "双重征税", ""),
        ("Tax Treaty", "税收协定", ""),
        ("Tax Return", "纳税申报表", ""),
        ("Taxable Income", "应税所得", ""),
        ("Progressive Tax", "累进税", ""),
        ("Regressive Tax", "累退税", ""),
        ("Transfer Pricing", "转让定价", ""),
        ("Permanent Establishment", "常设机构", ""),
    ],
    "环境法": [
        ("Environmental Law", "环境法", ""),
        ("Environmental Protection", "环境保护", ""),
        ("Pollution", "污染", ""),
        ("Air Pollution", "空气污染", ""),
        ("Water Pollution", "水污染", ""),
        ("Soil Contamination", "土壤污染", ""),
        ("Waste Management", "废物管理", ""),
        ("Hazardous Waste", "危险废物", ""),
        ("Carbon Emission", "碳排放", ""),
        ("Carbon Tax", "碳税", ""),
        ("Emission Standard", "排放标准", ""),
        ("Environmental Impact Assessment", "环境影响评价", "EIA"),
        ("Environmental Permitting", "环境许可", ""),
        ("Sustainable Development", "可持续发展", ""),
        ("Renewable Energy", "可再生能源", ""),
        ("Biodiversity", "生物多样性", ""),
        ("Climate Change", "气候变化", ""),
        ("Environmental Liability", "环境责任", ""),
        ("Pollution Prevention", "污染防治", ""),
        ("Environmental Audit", "环境审计", ""),
        ("Greenhouse Gas", "温室气体", ""),
        ("Paris Agreement", "巴黎协定", ""),
        ("Ecological Damage", "生态损害", ""),
        ("Environmental Regulation", "环境法规", ""),
    ],
}


# ==================== 工程/制造 术语库 ====================
ENGINEERING_GLOSSARY = {
    "工程通用": [
        ("Mechanism", "机构", ""),
        ("Component", "组件", ""),
        ("Assembly", "装配", ""),
        ("Fabrication", "制造", ""),
        ("Tolerance", "公差", ""),
        ("Specification", "规格", ""),
        ("Prototype", "原型", ""),
        ("Simulation", "仿真", ""),
        ("Finite Element Analysis", "有限元分析", "FEA"),
        ("Computational Fluid Dynamics", "计算流体力学", "CFD"),
        ("Thermodynamics", "热力学", ""),
        ("Fluid Dynamics", "流体动力学", ""),
        ("Stress Analysis", "应力分析", ""),
        ("Fatigue", "疲劳", ""),
        ("Corrosion", "腐蚀", ""),
        ("Actuator", "执行器", ""),
        ("Sensor", "传感器", ""),
        ("Controller", "控制器", ""),
        ("Automation", "自动化", ""),
        ("Robotics", "机器人", ""),
        ("Quality Control", "质量控制", "QC"),
        ("Six Sigma", "六西格玛", ""),
        ("Lean Manufacturing", "精益制造", ""),
        ("Supply Chain", "供应链", ""),
        ("Logistics", "物流", ""),
        ("Reliability", "可靠性", ""),
        ("Maintenance", "维护", ""),
        ("Mean Time Between Failures", "平均故障间隔时间", "MTBF"),
        ("Mean Time To Repair", "平均修复时间", "MTTR"),
    ],
    "机械工程": [
        ("Mechanical Engineering", "机械工程", ""),
        ("Machine Design", "机械设计", ""),
        ("Mechanical Component", "机械零件", ""),
        ("Bearing", "轴承", ""),
        ("Gear", "齿轮", ""),
        ("Shaft", "传动轴", ""),
        ("Pulley", "皮带轮", ""),
        ("Belt Drive", "带传动", ""),
        ("Chain Drive", "链传动", ""),
        ("Coupling", "联轴器", ""),
        ("Clutch", "离合器", ""),
        ("Brake", "制动器", ""),
        ("Crankshaft", "曲轴", ""),
        ("Piston", "活塞", ""),
        ("Cylinder", "气缸", ""),
        ("Valve", "阀门", ""),
        ("Pump", "泵", ""),
        ("Compressor", "压缩机", ""),
        ("Turbine", "涡轮机", ""),
        ("Lubrication", "润滑", ""),
        ("Friction", "摩擦", ""),
        ("Wear", "磨损", ""),
        ("Vibration Analysis", "振动分析", ""),
        ("Dynamic Balancing", "动平衡", ""),
        ("Mechanical Seal", "机械密封", ""),
        ("Thread", "螺纹", ""),
        ("Fastener", "紧固件", ""),
        ("Screw", "螺钉", ""),
        ("Gearbox", "齿轮箱", ""),
        ("Transmission", "传动系统", ""),
    ],
    "电子与电气": [
        ("Electronic Engineering", "电子工程", ""),
        ("Electrical Engineering", "电气工程", ""),
        ("Voltage", "电压", ""),
        ("Current", "电流", ""),
        ("Resistance", "电阻", ""),
        ("Capacitance", "电容", ""),
        ("Inductance", "电感", ""),
        ("Impedance", "阻抗", ""),
        ("Semiconductor", "半导体", ""),
        ("Transistor", "晶体管", ""),
        ("Diode", "二极管", ""),
        ("Integrated Circuit", "集成电路", "IC"),
        ("Printed Circuit Board", "印制电路板", "PCB"),
        ("Microcontroller", "微控制器", ""),
        ("Microprocessor", "微处理器", ""),
        ("Digital Signal Processing", "数字信号处理", "DSP"),
        ("Analog Circuit", "模拟电路", ""),
        ("Digital Circuit", "数字电路", ""),
        ("Power Supply", "电源", ""),
        ("Transformer", "变压器", ""),
        ("Rectifier", "整流器", ""),
        ("Amplifier", "放大器", ""),
        ("Oscillator", "振荡器", ""),
        ("Sensor", "传感器", ""),
        ("Actuator", "执行器", ""),
        ("Relay", "继电器", ""),
        ("Circuit Breaker", "断路器", ""),
        ("Fuse", "保险丝", ""),
        ("Insulation", "绝缘", ""),
        ("Electromagnetic Interference", "电磁干扰", "EMI"),
    ],
    "土木与建筑": [
        ("Civil Engineering", "土木工程", ""),
        ("Structural Engineering", "结构工程", ""),
        ("Building Construction", "建筑施工", ""),
        ("Foundation", "地基", ""),
        ("Load-Bearing Structure", "承重结构", ""),
        ("Reinforced Concrete", "钢筋混凝土", ""),
        ("Prestressed Concrete", "预应力混凝土", ""),
        ("Steel Structure", "钢结构", ""),
        ("Beam", "梁", ""),
        ("Column", "柱", ""),
        ("Slab", "楼板", ""),
        ("Truss", "桁架", ""),
        ("Bridge", "桥梁", ""),
        ("Tunnel", "隧道", ""),
        ("Dam", "水坝", ""),
        ("Road Engineering", "道路工程", ""),
        ("Highway", "公路", ""),
        ("Asphalt Pavement", "沥青路面", ""),
        ("Concrete Pavement", "混凝土路面", ""),
        ("Excavation", "开挖", ""),
        ("Piling", "打桩", ""),
        ("Scaffolding", "脚手架", ""),
        ("Seismic Design", "抗震设计", ""),
        ("Earthquake Resistance", "抗震性能", ""),
        ("Structural Analysis", "结构分析", ""),
        ("Hydraulic Engineering", "水利工程", ""),
        ("Drainage System", "排水系统", ""),
        ("Urban Planning", "城市规划", ""),
        ("Site Survey", "现场勘测", ""),
        ("Construction Supervision", "工程监理", ""),
    ],
    "航空航天": [
        ("Aerospace Engineering", "航空航天工程", ""),
        ("Aeronautics", "航空学", ""),
        ("Astronautics", "航天学", ""),
        ("Aircraft", "飞行器", ""),
        ("Airframe", "机身", ""),
        ("Fuselage", "机身", ""),
        ("Wing", "机翼", ""),
        ("Fuselage Structure", "机身结构", ""),
        ("Propulsion System", "推进系统", ""),
        ("Jet Engine", "喷气发动机", ""),
        ("Turbofan", "涡扇发动机", ""),
        ("Rocket Engine", "火箭发动机", ""),
        ("Thrust", "推力", ""),
        ("Lift", "升力", ""),
        ("Drag", "阻力", ""),
        ("Aerodynamics", "空气动力学", ""),
        ("Aerodynamic Drag", "气动阻力", ""),
        ("Flight Control System", "飞控系统", ""),
        ("Avionics", "航空电子", ""),
        ("Navigation System", "导航系统", ""),
        ("Payload", "有效载荷", ""),
        ("Orbit", "轨道", ""),
        ("Satellite", "卫星", ""),
        ("Spacecraft", "航天器", ""),
        ("Launch Vehicle", "运载火箭", ""),
        ("Reentry", "再入", ""),
        ("Aerodynamic Stability", "气动稳定性", ""),
        ("Cabin Pressurization", "座舱增压", ""),
        ("Flight Test", "试飞", ""),
        ("Air Traffic Control", "空中交通管制", "ATC"),
    ],
    "材料科学": [
        ("Materials Science", "材料科学", ""),
        ("Material Properties", "材料性能", ""),
        ("Tensile Strength", "抗拉强度", ""),
        ("Compressive Strength", "抗压强度", ""),
        ("Hardness", "硬度", ""),
        ("Ductility", "延展性", ""),
        ("Toughness", "韧性", ""),
        ("Elasticity", "弹性", ""),
        ("Plasticity", "塑性", ""),
        ("Fatigue Strength", "疲劳强度", ""),
        ("Yield Strength", "屈服强度", ""),
        ("Ultimate Tensile Strength", "极限抗拉强度", "UTS"),
        ("Alloy", "合金", ""),
        ("Stainless Steel", "不锈钢", ""),
        ("Aluminum Alloy", "铝合金", ""),
        ("Titanium Alloy", "钛合金", ""),
        ("Composite Material", "复合材料", ""),
        ("Ceramic", "陶瓷", ""),
        ("Polymer", "聚合物", ""),
        ("Plastic", "塑料", ""),
        ("Metallurgy", "冶金学", ""),
        ("Heat Treatment", "热处理", ""),
        ("Annealing", "退火", ""),
        ("Quenching", "淬火", ""),
        ("Casting", "铸造", ""),
        ("Forging", "锻造", ""),
        ("Welding", "焊接", ""),
        ("Surface Treatment", "表面处理", ""),
        ("Corrosion Resistance", "耐腐蚀性", ""),
        ("Microstructure", "微观结构", ""),
    ],
    "化学工程": [
        ("Chemical Engineering", "化学工程", ""),
        ("Chemical Reactor", "化学反应器", ""),
        ("Chemical Process", "化学工艺", ""),
        ("Unit Operation", "单元操作", ""),
        ("Distillation", "蒸馏", ""),
        ("Evaporation", "蒸发", ""),
        ("Crystallization", "结晶", ""),
        ("Filtration", "过滤", ""),
        ("Extraction", "萃取", ""),
        ("Absorption", "吸收", ""),
        ("Adsorption", "吸附", ""),
        ("Chemical Reaction", "化学反应", ""),
        ("Catalyst", "催化剂", ""),
        ("Catalytic Reaction", "催化反应", ""),
        ("Reaction Kinetics", "反应动力学", ""),
        ("Mass Transfer", "传质", ""),
        ("Heat Transfer", "传热", ""),
        ("Fluid Flow", "流体流动", ""),
        ("Fluidization", "流态化", ""),
        ("Reactor Design", "反应器设计", ""),
        ("Process Control", "过程控制", ""),
        ("Process Optimization", "过程优化", ""),
        ("Thermodynamics", "热力学", ""),
        ("Chemical Equilibrium", "化学平衡", ""),
        ("Stoichiometry", "化学计量学", ""),
        ("Corrosion", "腐蚀", ""),
        ("Piping", "管道", ""),
        ("Valve", "阀门", ""),
        ("Process Flow Diagram", "工艺流程图", "PFD"),
        ("Batch Process", "间歇过程", ""),
    ],
    "生产与质量管理": [
        ("Production Management", "生产管理", ""),
        ("Manufacturing", "制造", ""),
        ("Production Line", "生产线", ""),
        ("Assembly Line", "装配线", ""),
        ("Workstation", "工位", ""),
        ("Just-In-Time", "准时制生产", "JIT"),
        ("Kanban", "看板", ""),
        ("Total Quality Management", "全面质量管理", "TQM"),
        ("Statistical Process Control", "统计过程控制", "SPC"),
        ("Quality Assurance", "质量保证", "QA"),
        ("Quality Control", "质量控制", "QC"),
        ("Inspection", "检验", ""),
        ("Acceptance Sampling", "验收抽样", ""),
        ("Process Capability", "过程能力", ""),
        ("Control Chart", "控制图", ""),
        ("Failure Mode and Effects Analysis", "失效模式与影响分析", "FMEA"),
        ("Root Cause Analysis", "根本原因分析", "RCA"),
        ("Corrective Action", "纠正措施", ""),
        ("Preventive Action", "预防措施", ""),
        ("Standard Operating Procedure", "标准操作规程", "SOP"),
        ("Batch Number", "批号", ""),
        ("Traceability", "可追溯性", ""),
        ("Production Planning", "生产计划", ""),
        ("Capacity Planning", "产能规划", ""),
        ("Inventory Management", "库存管理", ""),
        ("Material Requirement Planning", "物料需求计划", "MRP"),
        ("Enterprise Resource Planning", "企业资源计划", "ERP"),
        ("Continuous Improvement", "持续改进", ""),
        ("Kaizen", "改善", ""),
        ("Lean Production", "精益生产", ""),
    ],
    "能源工程": [
        ("Energy Engineering", "能源工程", ""),
        ("Energy System", "能源系统", ""),
        ("Power Generation", "发电", ""),
        ("Electricity Generation", "电力生产", ""),
        ("Thermal Power", "火力发电", ""),
        ("Hydropower", "水力发电", ""),
        ("Nuclear Power", "核能发电", ""),
        ("Wind Power", "风力发电", ""),
        ("Solar Energy", "太阳能", ""),
        ("Photovoltaic", "光伏", "PV"),
        ("Solar Panel", "太阳能电池板", ""),
        ("Geothermal Energy", "地热能", ""),
        ("Biomass Energy", "生物质能", ""),
        ("Hydrogen Energy", "氢能", ""),
        ("Fuel Cell", "燃料电池", ""),
        ("Energy Efficiency", "能源效率", ""),
        ("Energy Consumption", "能源消耗", ""),
        ("Energy Storage", "储能", ""),
        ("Battery", "电池", ""),
        ("Lithium-Ion Battery", "锂离子电池", ""),
        ("Power Grid", "电网", ""),
        ("Smart Grid", "智能电网", ""),
        ("Power Distribution", "配电", ""),
        ("Power Transmission", "输电", ""),
        ("Load Management", "负荷管理", ""),
        ("Peak Demand", "峰值需求", ""),
        ("Renewable Energy", "可再生能源", ""),
        ("Carbon Neutrality", "碳中和", ""),
        ("Energy Conservation", "节能", ""),
        ("Grid Connection", "并网", ""),
    ],
    "汽车工程": [
        ("Automotive Engineering", "汽车工程", ""),
        ("Internal Combustion Engine", "内燃机", "ICE"),
        ("Gasoline Engine", "汽油发动机", ""),
        ("Diesel Engine", "柴油发动机", ""),
        ("Electric Vehicle", "电动汽车", "EV"),
        ("Hybrid Electric Vehicle", "混合动力汽车", "HEV"),
        ("Fuel Cell Vehicle", "燃料电池汽车", "FCV"),
        ("Battery Electric Vehicle", "纯电动汽车", "BEV"),
        ("Transmission System", "变速系统", ""),
        ("Chassis", "底盘", ""),
        ("Suspension System", "悬挂系统", ""),
        ("Steering System", "转向系统", ""),
        ("Braking System", "制动系统", ""),
        ("Drivetrain", "传动系统", ""),
        ("Axle", "车轴", ""),
        ("Wheel Alignment", "车轮定位", ""),
        ("Engine Control Unit", "发动机控制单元", "ECU"),
        ("Vehicle Dynamics", "车辆动力学", ""),
        ("Aerodynamic Drag", "空气阻力", ""),
        ("Fuel Consumption", "油耗", ""),
        ("Fuel Efficiency", "燃油效率", ""),
        ("Exhaust Emission", "尾气排放", ""),
        ("Emission Control", "排放控制", ""),
        ("Crashworthiness", "碰撞安全性", ""),
        ("Airbag", "安全气囊", ""),
        ("Antilock Braking System", "防抱死制动系统", "ABS"),
        ("Electronic Stability Control", "电子稳定控制系统", "ESC"),
        ("Advanced Driver Assistance System", "高级驾驶辅助系统", "ADAS"),
        ("Autonomous Driving", "自动驾驶", ""),
        ("Vehicle-to-Everything", "车联网通信", "V2X"),
    ],
    "海洋与船舶工程": [
        ("Ocean Engineering", "海洋工程", ""),
        ("Naval Architecture", "船舶工程", ""),
        ("Ship Design", "船舶设计", ""),
        ("Hull", "船体", ""),
        ("Hull Structure", "船体结构", ""),
        ("Ship Propulsion", "船舶推进", ""),
        ("Propeller", "螺旋桨", ""),
        ("Stern", "船尾", ""),
        ("Bow", "船首", ""),
        ("Draft", "吃水深度", ""),
        ("Displacement", "排水量", ""),
        ("Buoyancy", "浮力", ""),
        ("Ballast", "压载", ""),
        ("Offshore Platform", "海上平台", ""),
        ("Subsea Pipeline", "海底管道", ""),
        ("Marine Structure", "海洋结构物", ""),
        ("Deep-Sea Mining", "深海采矿", ""),
        ("Coastal Engineering", "海岸工程", ""),
        ("Marine Environment", "海洋环境", ""),
        ("Seaworthiness", "适航性", ""),
        ("Ship Stability", "船舶稳性", ""),
        ("Marine Corrosion", "海洋腐蚀", ""),
        ("Underwater Vehicle", "水下航行器", ""),
        ("Remotely Operated Vehicle", "遥控潜水器", "ROV"),
        ("Autonomous Underwater Vehicle", "自主式水下航行器", "AUV"),
        ("Harbor Engineering", "港口工程", ""),
        ("Maritime Transport", "海上运输", ""),
        ("Shipbuilding", "船舶建造", ""),
        ("Marine Survey", "海事测量", ""),
        ("Ocean Current", "洋流", ""),
    ],
}


ALL_PRESET_GLOSSARIES = {
    **{f"AI/{k}": v for k, v in AI_CS_GLOSSARY.items()},
    **{f"医学/{k}": v for k, v in MEDICAL_GLOSSARY.items()},
    **{f"金融/{k}": v for k, v in FINANCE_GLOSSARY.items()},
    **{f"法律/{k}": v for k, v in LEGAL_GLOSSARY.items()},
    **{f"工程/{k}": v for k, v in ENGINEERING_GLOSSARY.items()},
}


def get_all_terms(domain: str = None) -> list:
    """获取所有术语列表
    
    Args:
        domain: 可选，仅获取指定领域的术语（如 "AI/通用 AI", "医学/肿瘤学"）
    """
    terms = []
    source = ALL_PRESET_GLOSSARIES
    if domain:
        source = {domain: ALL_PRESET_GLOSSARIES.get(domain, [])}
    for domain_name, term_list in source.items():
        for term, translation, abbreviation in term_list:
            terms.append({
                "term": term,
                "translation": translation,
                "lang_in": "en",
                "lang_out": "zh",
                "domain": domain_name,
                "description": abbreviation,
            })
    return terms


def get_terms_by_domain(domain: str) -> list:
    """获取指定领域的术语"""
    return get_all_terms(domain=domain)


def get_domains() -> list:
    """获取所有顶级领域列表"""
    top_domains = set()
    for key in ALL_PRESET_GLOSSARIES:
        top = key.split("/")[0]
        top_domains.add(top)
    return sorted(top_domains)


def get_sub_domains(top_domain: str = None) -> list:
    """获取所有子领域列表
    
    Args:
        top_domain: 顶级领域名（如 "AI"），为 None 返回全部
    """
    if top_domain:
        return [k for k in ALL_PRESET_GLOSSARIES if k.startswith(top_domain + "/")]
    return list(ALL_PRESET_GLOSSARIES.keys())


if __name__ == "__main__":
    import logging
    _logger = logging.getLogger(__name__)
    total = sum(len(v) for v in ALL_PRESET_GLOSSARIES.values())
    _logger.info("多领域术语库统计:")
    _logger.info("  总术语数: %d", total)
    _logger.info("  子领域数: %d", len(ALL_PRESET_GLOSSARIES))
    top = {}
    for domain_name, terms in ALL_PRESET_GLOSSARIES.items():
        top_key = domain_name.split("/")[0]
        top[top_key] = top.get(top_key, 0) + len(terms)
    for k, v in sorted(top.items()):
        _logger.info("  %s: %d 条", k, v)